// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BackgroundOrigin from "./BackgroundOrigin.js";
import * as Css from "@vanilla-extract/css";

var options = BackgroundOrigin.BackgroundOrigin.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                backgroundOrigin: value
              };
      }));

var BackgroundOriginStyle_initial = BackgroundOrigin.BackgroundOrigin.initial;

var BackgroundOriginStyle = {
  initial: BackgroundOriginStyle_initial,
  options: options,
  style: style
};

export {
  BackgroundOriginStyle ,
  
}
/* style Not a pure module */
