// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  borderBox: "border-box",
  paddingBox: "padding-box",
  contentBox: "content-box",
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset"
};

var BackgroundOrigin = {
  initial: "paddingBox",
  options: options
};

export {
  BackgroundOrigin ,
  
}
/* No side effect */
