// Generated by ReScript, PLEASE EDIT WITH CARE


var args = [
  "thin",
  "bold",
  "initial"
];

var initial = "initial";

var options = {
  thin: "1px",
  bold: "3px",
  initial: "initial"
};

export {
  args ,
  initial ,
  options ,
  
}
/* No side effect */
