// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@vanilla-extract/css";
import * as TextDecorationThickness from "./TextDecorationThickness.js";

var make = Css.styleVariants(TextDecorationThickness.options, (function (value) {
        return {
                textDecorationThickness: value
              };
      }));

var options = TextDecorationThickness.options;

export {
  options ,
  make ,
  
}
/* make Not a pure module */
