// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@vanilla-extract/css";
import * as TextDecorationThickness from "./TextDecorationThickness.js";

var options = TextDecorationThickness.TextDecorationThickness.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                textDecorationThickness: value
              };
      }));

var TextDecorationThicknessStyle_initial = TextDecorationThickness.TextDecorationThickness.initial;

var TextDecorationThicknessStyle = {
  initial: TextDecorationThicknessStyle_initial,
  options: options,
  style: style
};

export {
  TextDecorationThicknessStyle ,
  
}
/* style Not a pure module */
