// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  auto: "auto",
  fromFont: "fromFont",
  thin: "1px",
  light: "2px",
  medium: "3px",
  bold: "4px",
  inherit: "inheritValue",
  initial: "initial",
  unset: "unset"
};

var TextDecorationThickness = {
  initial: "initial",
  options: options
};

export {
  TextDecorationThickness ,
  
}
/* No side effect */
