// Generated by ReScript, PLEASE EDIT WITH CARE


function get(t) {
  console.log(t._0);
  
}

var q = get(/* TextColor */{
      _0: "primary"
    });

var TextColor = {
  get: get,
  q: q
};

export {
  TextColor ,
  
}
/* q Not a pure module */
