// Generated by ReScript, PLEASE EDIT WITH CARE

import * as InteractiveVariant from "./InteractiveVariant.js";
import * as Css from "@vanilla-extract/css";

var options = InteractiveVariant.InteractiveVariant.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                color: value.color,
                borderColor: value.borderColor,
                backgroundColor: value.backgroundColor,
                borderStyle: "solid",
                outlineStyle: "none",
                transition: ".2s color ease-in, .2s border ease-in, .2s background ease-in"
              };
      }));

var InteractiveVariantStyle_key = InteractiveVariant.InteractiveVariant.key;

var InteractiveVariantStyle_initial = InteractiveVariant.InteractiveVariant.initial;

var InteractiveVariantStyle = {
  key: InteractiveVariantStyle_key,
  initial: InteractiveVariantStyle_initial,
  options: options,
  style: style
};

export {
  InteractiveVariantStyle ,
  
}
/* style Not a pure module */
