// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  solid: {
    color: "var(--text-color)",
    backgroundColor: "var(--color)",
    borderColor: "var(--color)"
  },
  ghost: {
    color: "var(--color)",
    backgroundColor: "transparent",
    borderColor: "var(--color)"
  },
  borderless: {
    color: "var(--color)",
    backgroundColor: "hsl(var(--h) var(--s) 90% / var(--a))",
    borderColor: "hsl(var(--h) var(--s) 90% / var(--a))"
  },
  text: {
    color: "var(--color)",
    backgroundColor: "transparent",
    borderColor: "transparent"
  }
};

var InteractiveVariant = {
  key: "interactiveVariant",
  initial: "solid",
  options: options
};

export {
  InteractiveVariant ,
  
}
/* No side effect */
