// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  inside: "inside",
  outside: "outside"
};

var QuotePosition = {
  key: "quotePosition",
  initial: "outside",
  options: options
};

export {
  QuotePosition ,
  
}
/* No side effect */
