// Generated by ReScript, PLEASE EDIT WITH CARE

import * as QuotePosition from "./QuotePosition.js";
import * as Css from "@vanilla-extract/css";

var options = QuotePosition.QuotePosition.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--quote-position": value
              };
      }));

var QuotePositionStyle_initial = QuotePosition.QuotePosition.initial;

var QuotePositionStyle = {
  initial: QuotePositionStyle_initial,
  options: options,
  style: style
};

export {
  QuotePositionStyle ,
  
}
/* style Not a pure module */
