export { default as Capitalize } from './Capitalize'
export { default as LineThrough } from './LineThrough'
export { default as Lowercase } from './Lowercase'
export { default as StressEmphasis } from './StressEmphasis'
export { default as Strong } from './Strong'
export { default as Thin } from './Thin'
export { default as Underline } from './Underline'
export { default as Uppercase } from './Uppercase'
