// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextTransformResolver from "./Transform/TextTransformResolver.js";

function resolve(textTransform) {
  return TextTransformResolver.make(textTransform);
}

export {
  resolve ,
  
}
/* TextTransformResolver Not a pure module */
