// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextTransformStyleCssJs from "./Transform/TextTransformStyle.css.js";

var textTransform = TextTransformStyleCssJs.TextTransformStyle;

function resolve(i) {
  var match = i.textTransform;
  return [match === "none" ? textTransform.style.none : (
                match === "capitalize" ? textTransform.style.capitalize : (
                    match === "lowercase" ? textTransform.style.lowercase : (
                        match === "uppercase" ? textTransform.style.uppercase : (
                            match === "fullSizeKana" ? textTransform.style.fullSizeKana : textTransform.style.fullWidth
                          )
                      )
                  )
              )].join(" ");
}

var TextTransformLayer = {
  resolve: resolve
};

export {
  textTransform ,
  TextTransformLayer ,
  
}
/* textTransform Not a pure module */
