// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.js";
import * as TextTransformStyleCssJs from "./Transform/TextTransformStyle.css.js";

var transform = TextTransformStyleCssJs.TextTransformStyle;

function resolve(textTransform) {
  return Cx.cx([textTransform === "none" ? transform.style.none : (
                  textTransform === "capitalize" ? transform.style.capitalize : (
                      textTransform === "lowercase" ? transform.style.lowercase : (
                          textTransform === "uppercase" ? transform.style.uppercase : (
                              textTransform === "fullSizeKana" ? transform.style.fullSizeKana : transform.style.fullWidth
                            )
                        )
                    )
                )]);
}

var TextTransformLayer = {
  resolve: resolve
};

export {
  transform ,
  TextTransformLayer ,
  
}
/* transform Not a pure module */
