// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ButtonVariant from "./ButtonVariant.js";
import * as Css from "@vanilla-extract/css";

var options = ButtonVariant.ButtonVariant.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                color: value.color,
                borderColor: value.borderColor,
                backgroundColor: value.backgroundColor,
                borderStyle: "solid",
                outlineStyle: "none",
                transition: ".2s color ease-in, .2s border ease-in, .2s background ease-in",
                ":hover": value[":hover"],
                ":active": value[":active"],
                ":focus": value[":focus"],
                ":disabled": value[":disabled"]
              };
      }));

var ButtonVariantStyle_key = ButtonVariant.ButtonVariant.key;

var ButtonVariantStyle_initial = ButtonVariant.ButtonVariant.initial;

var ButtonVariantStyle = {
  key: ButtonVariantStyle_key,
  initial: ButtonVariantStyle_initial,
  options: options,
  style: style
};

export {
  ButtonVariantStyle ,
  
}
/* style Not a pure module */
