// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextOverflow from "./TextOverflow.js";
import * as Css from "@vanilla-extract/css";

var options = TextOverflow.TextOverflow.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                textOverflow: value
              };
      }));

var TextOverflowStyle_key = TextOverflow.TextOverflow.key;

var TextOverflowStyle_initial = TextOverflow.TextOverflow.initial;

var TextOverflowStyle = {
  key: TextOverflowStyle_key,
  initial: TextOverflowStyle_initial,
  options: options,
  style: style
};

export {
  TextOverflowStyle ,
  
}
/* style Not a pure module */
