// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  clip: "clip",
  ellipsis: "ellipsis",
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset"
};

var TextOverflow = {
  key: "textOverflow",
  initial: "clip",
  options: options
};

export {
  TextOverflow ,
  
}
/* No side effect */
