// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OverlayColorStyleCssJs from "./OverlayColorStyle.css.js";

var color = OverlayColorStyleCssJs.OverlayColorStyle;

function resolve(i) {
  var match = i.color;
  return [match === "secondary" ? color.style.secondary : (
                match === "primary" ? color.style.primary : (
                    match === "black" ? color.style.black : color.style.white
                  )
              )].join(" ");
}

var OverlayColorLayer = {
  resolve: resolve
};

export {
  color ,
  OverlayColorLayer ,
  
}
/* color Not a pure module */
