// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ColorReflection from "../ColorReflection.js";

var options = {
  primary: "#0078D4",
  secondary: "#2B88D8",
  black: "#000000",
  white: "#FFFFFF"
};

var OverlayColor_key = ColorReflection.ColorReflection.key;

var OverlayColor_initial = ColorReflection.ColorReflection.initial;

var OverlayColor = {
  key: OverlayColor_key,
  initial: OverlayColor_initial,
  options: options
};

export {
  OverlayColor ,
  
}
/* No side effect */
