// Generated by ReScript, PLEASE EDIT WITH CARE

import * as QuoteGap from "./QuoteGap.js";
import * as Css from "@vanilla-extract/css";

var options = QuoteGap.QuoteGap.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--quote-gap": value
              };
      }));

var QuoteGapStyle_initial = QuoteGap.QuoteGap.initial;

var QuoteGapStyle = {
  initial: QuoteGapStyle_initial,
  options: options,
  style: style
};

export {
  QuoteGapStyle ,
  
}
/* style Not a pure module */
