// Generated by ReScript, PLEASE EDIT WITH CARE

function get(t) {
  switch (t.TAG | 0) {
    case /* Padding */ 0:
      console.log(t.padding)
      return
    case /* PaddingXY */ 1:
      console.log(t.paddingX + t.paddingY)
      return
    case /* PaddingTRBL */ 2:
      console.log(
        t.paddingTop + t.paddingRight + t.paddingBottom + t.paddingLeft
      )
      return
  }
}

var q = get({
  TAG: /* PaddingXY */ 1,
  paddingX: 'large',
  paddingY: 'small',
})

var Padding = {
  get: get,
  q: q,
}

export { Padding }
/* q Not a pure module */
