/* TypeScript file generated from HTML.res by genType. */
/* eslint-disable import/first */

// tslint:disable-next-line:interface-over-type-literal
export type HTML_content =
  | 'None'
  | 'Empty'
  | 'Transparent'
  | 'Metadata'
  | 'Flow'
  | 'Sectioning'
  | 'Heading'
  | 'Phrasing'
  | 'Embedded'
  | 'Interactive'
  | 'Palpable'
  | 'FormAssociated'
  | 'ScriptSupportingElements'

// tslint:disable-next-line:interface-over-type-literal
export type HTML_ariaRole =
  | 'None'
  | 'Any'
  | 'Group'
  | 'Heading'
  | 'Tab'
  | 'Presentation'
  | 'Link'
  | 'Button'
  | 'Checkbox'
  | 'MenuItem'
  | 'MenuItemCheckbox'
  | 'MenuItemRadio'
  | 'Option'
  | 'Radio'
  | 'Switch'
  | 'TreeItem'
  | 'Term'
  | 'Separator'

// tslint:disable-next-line:interface-over-type-literal
export type HTML_tag =
  | 'A'
  | 'Abbr'
  | 'B'
  | 'Br'
  | 'Cite'
  | 'Code'
  | 'Data'
  | 'Dfn'
  | 'Div'
  | 'Em'
  | 'Figcaption'
  | 'H1'
  | 'H2'
  | 'H3'
  | 'H4'
  | 'H5'
  | 'H6'
  | 'Hr'
  | 'I'
  | 'Kbd'
  | 'Mark'
  | 'P'
  | 'S'
  | 'Samp'
  | 'Small'
  | 'Span'
  | 'Strong'
  | 'Sub'
  | 'Sup'
  | 'Time'
  | 'U'
  | 'Var'
  | 'Wbr'

// tslint:disable-next-line:interface-over-type-literal
export type HTML_semanticallyNeutralTags = 'Div' | 'Span'
