// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarginReflection from "../MarginReflection.js";
import * as Css from "@vanilla-extract/css";

var make = Css.styleVariants(MarginReflection.options, (function (value) {
        return {
                marginInlineEnd: value
              };
      }));

var options = MarginReflection.options;

export {
  options ,
  make ,
  
}
/* make Not a pure module */
