// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Margin from "../Margin.js";

var MarginInlineEnd_initial = Margin.Margin.initial;

var MarginInlineEnd_options = Margin.Margin.options;

var MarginInlineEnd = {
  initial: MarginInlineEnd_initial,
  options: MarginInlineEnd_options
};

export {
  MarginInlineEnd ,
  
}
/* No side effect */
