// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarginReflection from "../MarginReflection.js";

var MarginInlineEnd_initial = MarginReflection.MarginReflection.initial;

var MarginInlineEnd_options = MarginReflection.MarginReflection.options;

var MarginInlineEnd = {
  initial: MarginInlineEnd_initial,
  options: MarginInlineEnd_options,
  key: "marginInlineEnd"
};

export {
  MarginInlineEnd ,
  
}
/* No side effect */
