// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarginInlineEnd from "./MarginInlineEnd.js";
import * as Css from "@vanilla-extract/css";

var options = MarginInlineEnd.MarginInlineEnd.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                marginInlineEnd: value
              };
      }));

var MarginInlineEndStyle_initial = MarginInlineEnd.MarginInlineEnd.initial;

var MarginInlineEndStyle_key = MarginInlineEnd.MarginInlineEnd.key;

var MarginInlineEndStyle = {
  initial: MarginInlineEndStyle_initial,
  options: options,
  key: MarginInlineEndStyle_key,
  style: style
};

export {
  MarginInlineEndStyle ,
  
}
/* style Not a pure module */
