// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarginBlockEndStyleCssJs from "./BlockEnd/MarginBlockEndStyle.css.js";
import * as MarginInlineEndStyleCssJs from "./InlineEnd/MarginInlineEndStyle.css.js";
import * as MarginBlockStartStyleCssJs from "./BlockStart/MarginBlockStartStyle.css.js";
import * as MarginInlineStartStyleCssJs from "./InlineStart/MarginInlineStartStyle.css.js";

var marginBlockEnd = MarginBlockEndStyleCssJs.MarginBlockEndStyle;

var marginBlockStart = MarginBlockStartStyleCssJs.MarginBlockStartStyle;

var marginInlineEnd = MarginInlineEndStyleCssJs.MarginInlineEndStyle;

var marginInlineStart = MarginInlineStartStyleCssJs.MarginInlineStartStyle;

function resolve(i) {
  var match = i.marginBlockEnd;
  var match$1 = i.marginBlockStart;
  var match$2 = i.marginInlineEnd;
  var match$3 = i.marginInlineStart;
  return [
            match === "none" ? marginBlockEnd.style.none : (
                match === "xxlarge" ? marginBlockEnd.style.xxlarge : (
                    match === "xlarge" ? marginBlockEnd.style.xlarge : (
                        match === "large" ? marginBlockEnd.style.large : (
                            match === "xxsmall" ? marginBlockEnd.style.xxsmall : (
                                match === "xsmall" ? marginBlockEnd.style.xsmall : (
                                    match === "medium" ? marginBlockEnd.style.medium : (
                                        match === "small" ? marginBlockEnd.style.small : (
                                            match === "xxxlarge" ? marginBlockEnd.style.xxxlarge : marginBlockEnd.style.xxxsmall
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$1 === "none" ? marginBlockStart.style.none : (
                match$1 === "xxlarge" ? marginBlockStart.style.xxlarge : (
                    match$1 === "xlarge" ? marginBlockStart.style.xlarge : (
                        match$1 === "large" ? marginBlockStart.style.large : (
                            match$1 === "xxsmall" ? marginBlockStart.style.xxsmall : (
                                match$1 === "xsmall" ? marginBlockStart.style.xsmall : (
                                    match$1 === "medium" ? marginBlockStart.style.medium : (
                                        match$1 === "small" ? marginBlockStart.style.small : (
                                            match$1 === "xxxlarge" ? marginBlockStart.style.xxxlarge : marginBlockStart.style.xxxsmall
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$2 === "none" ? marginInlineEnd.style.none : (
                match$2 === "xxlarge" ? marginInlineEnd.style.xxlarge : (
                    match$2 === "xlarge" ? marginInlineEnd.style.xlarge : (
                        match$2 === "large" ? marginInlineEnd.style.large : (
                            match$2 === "xxsmall" ? marginInlineEnd.style.xxsmall : (
                                match$2 === "xsmall" ? marginInlineEnd.style.xsmall : (
                                    match$2 === "medium" ? marginInlineEnd.style.medium : (
                                        match$2 === "small" ? marginInlineEnd.style.small : (
                                            match$2 === "xxxlarge" ? marginInlineEnd.style.xxxlarge : marginInlineEnd.style.xxxsmall
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$3 === "none" ? marginInlineStart.style.none : (
                match$3 === "xxlarge" ? marginInlineStart.style.xxlarge : (
                    match$3 === "xlarge" ? marginInlineStart.style.xlarge : (
                        match$3 === "large" ? marginInlineStart.style.large : (
                            match$3 === "xxsmall" ? marginInlineStart.style.xxsmall : (
                                match$3 === "xsmall" ? marginInlineStart.style.xsmall : (
                                    match$3 === "medium" ? marginInlineStart.style.medium : (
                                        match$3 === "small" ? marginInlineStart.style.small : (
                                            match$3 === "xxxlarge" ? marginInlineStart.style.xxxlarge : marginInlineStart.style.xxxsmall
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              )
          ].join(" ");
}

var MarginLayer = {
  resolve: resolve
};

export {
  marginBlockEnd ,
  marginBlockStart ,
  marginInlineEnd ,
  marginInlineStart ,
  MarginLayer ,
  
}
/* marginBlockEnd Not a pure module */
