// Generated by ReScript, PLEASE EDIT WITH CARE


var args = [
  "size0",
  "size50",
  "size100",
  "size150",
  "size200",
  "size250",
  "size300",
  "size350",
  "size400",
  "size450",
  "size500",
  "size550",
  "size600",
  "size700",
  "size800"
];

var initial = "size0";

var options = {
  size0: "0px",
  size50: "4px",
  size100: "8px",
  size150: "12px",
  size200: "16px",
  size250: "20px",
  size300: "24px",
  size350: "28px",
  size400: "32px",
  size450: "36px",
  size500: "40px",
  size550: "44px",
  size600: "48px",
  size700: "56px",
  size800: "64px"
};

export {
  args ,
  initial ,
  options ,
  
}
/* No side effect */
