// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextTransform from "./TextTransform.js";
import * as Css from "@vanilla-extract/css";

var options = TextTransform.TextTransform.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                textTransform: value
              };
      }));

var TextTransformStyle_initial = TextTransform.TextTransform.initial;

var TextTransformStyle = {
  initial: TextTransformStyle_initial,
  options: options,
  style: style
};

export {
  TextTransformStyle ,
  
}
/* style Not a pure module */
