// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: "none",
  uppercase: "uppercase",
  lowercase: "lowercase",
  capitalize: "capitalize",
  fullWidth: "full-width",
  fullSizeKana: "full-size-kana"
};

var TextTransform = {
  initial: "none",
  options: options
};

export {
  TextTransform ,
  
}
/* No side effect */
