// Generated by ReScript, PLEASE EDIT WITH CARE


var args = [
  "none",
  "uppercase",
  "lowercase",
  "capitalize"
];

var initial = "none";

var options = {
  none: "none",
  uppercase: "uppercase",
  lowercase: "lowercase",
  capitalize: "capitalize"
};

export {
  args ,
  initial ,
  options ,
  
}
/* No side effect */
