// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextTransform from "./TextTransform.js";
import * as Css from "@vanilla-extract/css";

var make = Css.styleVariants(TextTransform.options, (function (value) {
        return {
                textTransform: value
              };
      }));

var options = TextTransform.options;

export {
  options ,
  make ,
  
}
/* make Not a pure module */
