const path = require('path')
const { VanillaExtractPlugin } = require('@vanilla-extract/webpack-plugin')
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

module.exports = {
  components: './src/index.ts',
  outputPath: './playroom',

  snippets: './src/snippets/index.tsx',
  widths: [320, 768, 1024],
  port: 9000,
  openBrowser: true,
  paramType: 'search', // default is 'hash'
  exampleCode: `
    <Title>
      Заголовок страницы
    </Title>

    <Frame charsPerLine="large">
      <H1>Заголовок первого уровня</H1>
      <Paragraph>Многострочный текст</Paragraph>
    </Frame>
  `,
  baseUrl: './',
  webpackConfig: () => ({
    plugins: [
      new VanillaExtractPlugin(/* { allowRuntime: true } */),
      new MiniCssExtractPlugin(),
    ],
    module: {
      rules: [
        {
          test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
          use: [
            MiniCssExtractPlugin.loader,
            {
              loader: require.resolve('css-loader'),
              options: {
                url: false, // Required as image imports should be handled via JS/TS import statements
              },
            },
          ],
        },
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              presets: [
                '@babel/preset-env',
                '@babel/preset-typescript',
                '@babel/preset-react',
              ],
            },
          },
        },
      ],
    },
    resolve: {
      extensions: ['.js', '.ts', '.tsx'],
      alias: {
        axioms: path.resolve(__dirname, 'src/axioms/'),
        CSS: path.resolve(__dirname, 'src/CSS/'),
        button: path.resolve(__dirname, 'src/button/'),
        dialog: path.resolve(__dirname, 'src/dialog/'),
        form: path.resolve(__dirname, 'src/form/'),
        image: path.resolve(__dirname, 'src/image/'),
        layers: path.resolve(__dirname, 'src/layers/'),
        layout: path.resolve(__dirname, 'src/layout/'),
        typography: path.resolve(__dirname, 'src/typography/'),
        utils: path.resolve(__dirname, 'src/utils/'),
      },
    },
  }),
  iframeSandbox: 'allow-scripts',
  frameComponent: './playroom/Frame.tsx',
  typeScriptFiles: ['src/**/*.{ts,tsx}', '!**/node_modules'],
}
