// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PaddingReflection from "../PaddingReflection.js";

var PaddingBlockStart_initial = PaddingReflection.PaddingReflection.initial;

var PaddingBlockStart_options = PaddingReflection.PaddingReflection.options;

var PaddingBlockStart = {
  initial: PaddingBlockStart_initial,
  options: PaddingBlockStart_options,
  key: "paddingBlockStart"
};

export {
  PaddingBlockStart ,
  
}
/* No side effect */
