// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PaddingBlockStart from "./PaddingBlockStart.js";
import * as Css from "@vanilla-extract/css";

var options = PaddingBlockStart.PaddingBlockStart.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                paddingBlockStart: value
              };
      }));

var PaddingBlockStartStyle_initial = PaddingBlockStart.PaddingBlockStart.initial;

var PaddingBlockStartStyle = {
  initial: PaddingBlockStartStyle_initial,
  options: options,
  style: style
};

export {
  PaddingBlockStartStyle ,
  
}
/* style Not a pure module */
