// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Padding from "../Padding.js";

var PaddingBlockStart_initial = Padding.Padding.initial;

var PaddingBlockStart_options = Padding.Padding.options;

var PaddingBlockStart = {
  initial: PaddingBlockStart_initial,
  options: PaddingBlockStart_options
};

export {
  PaddingBlockStart ,
  
}
/* No side effect */
