// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  row: "row",
  rowReverse: "row-reverse",
  column: "column",
  columnReverse: "column-Reverse"
};

var FlexDirection = {
  key: "flexDirection",
  initial: "row",
  options: options
};

export {
  FlexDirection ,
  
}
/* No side effect */
