// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FlexDirection from "./FlexDirection.js";
import * as Css from "@vanilla-extract/css";

var options = FlexDirection.FlexDirection.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                flexDirection: value
              };
      }));

var FlexDirectionStyle_initial = FlexDirection.FlexDirection.initial;

var FlexDirectionStyle = {
  initial: FlexDirectionStyle_initial,
  options: options,
  style: style
};

export {
  FlexDirectionStyle ,
  
}
/* style Not a pure module */
