// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "../../../../theme/Theme.js";

var args = [
  "currentColor",
  "primary",
  "secondary",
  "black",
  "white"
];

var options_primary = Theme.color.primary;

var options_secondary = Theme.color.secondary;

var options_black = Theme.color.black;

var options_white = Theme.color.white;

var options = {
  currentColor: "currentColor",
  primary: options_primary,
  secondary: options_secondary,
  black: options_black,
  white: options_white
};

var initial = "currentColor";

export {
  args ,
  initial ,
  options ,
  
}
/* No side effect */
