// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextDecorationColor from "./TextDecorationColor.js";
import * as Css from "@vanilla-extract/css";

var options = TextDecorationColor.TextDecorationColor.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                textDecorationColor: value
              };
      }));

var TextDecorationColorStyle_initial = TextDecorationColor.TextDecorationColor.initial;

var TextDecorationColorStyle = {
  initial: TextDecorationColorStyle_initial,
  options: options,
  style: style
};

export {
  TextDecorationColorStyle ,
  
}
/* style Not a pure module */
