// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextDecorationColor from "./TextDecorationColor.js";
import * as Css from "@vanilla-extract/css";

var make = Css.styleVariants(TextDecorationColor.options, (function (value) {
        return {
                textDecorationColor: value
              };
      }));

var options = TextDecorationColor.options;

export {
  options ,
  make ,
  
}
/* make Not a pure module */
