// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  currentColor: "currentColor",
  primary: "#0078D4",
  secondary: "#2B88D8",
  black: "#000000",
  white: "#FFFFFF"
};

var TextDecorationColor = {
  initial: "currentColor",
  options: options
};

export {
  TextDecorationColor ,
  
}
/* No side effect */
