// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  normal: "normal",
  breakWord: "break-word",
  anywhere: "anywhere",
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset"
};

var OverflowWrap = {
  key: "overflowWrap",
  initial: "normal",
  options: options
};

export {
  OverflowWrap ,
  
}
/* No side effect */
