// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OverflowWrap from "./OverflowWrap.js";
import * as Css from "@vanilla-extract/css";

var options = OverflowWrap.OverflowWrap.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                overflowWrap: value
              };
      }));

var OverflowWrapStyle_key = OverflowWrap.OverflowWrap.key;

var OverflowWrapStyle_initial = OverflowWrap.OverflowWrap.initial;

var OverflowWrapStyle = {
  key: OverflowWrapStyle_key,
  initial: OverflowWrapStyle_initial,
  options: options,
  style: style
};

export {
  OverflowWrapStyle ,
  
}
/* style Not a pure module */
