// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "../../../theme/Theme.js";
import * as React from "react";
import * as ColorReflection from "../ColorReflection.js";

var options_primary = Theme.color.primary;

var options_secondary = Theme.color.secondary;

var options_black = Theme.color.black;

var options_white = Theme.color.white;

var options = {
  primary: options_primary,
  secondary: options_secondary,
  black: options_black,
  white: options_white
};

var context = React.createContext(undefined);

function useColor(param) {
  return React.useContext(context);
}

var provider = context.Provider;

function Color$component(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var args = ColorReflection.args;

var initial = ColorReflection.initial;

var component = Color$component;

export {
  args ,
  options ,
  initial ,
  context ,
  useColor ,
  provider ,
  component ,
  
}
/* context Not a pure module */
