// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  primary: "#0078D4",
  secondary: "#2B88D8",
  black: "#000000",
  white: "#FFFFFF"
};

var Color = {
  initial: "primary",
  options: options
};

export {
  Color ,
  
}
/* No side effect */
