// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Color from "./Color.js";
import * as Css from "@vanilla-extract/css";

var make = Css.styleVariants(Color.options, (function (value) {
        return {
                color: value
              };
      }));

var options = Color.options;

export {
  options ,
  make ,
  
}
/* make Not a pure module */
