// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.js";
import * as ColorStyleCssJs from "./ColorStyle.css.js";

var colorStyle = ColorStyleCssJs.ColorStyle;

function resolve(color) {
  return Cx.cx([color === "secondary" ? colorStyle.style.secondary : (
                  color === "primary" ? colorStyle.style.primary : (
                      color === "black" ? colorStyle.style.black : colorStyle.style.white
                    )
                )]);
}

var ColorLayer = {
  resolve: resolve
};

export {
  colorStyle ,
  ColorLayer ,
  
}
/* colorStyle Not a pure module */
