// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ColorResolver from "./ColorResolver.js";

function resolve(color) {
  return ColorResolver.make(color);
}

export {
  resolve ,
  
}
/* ColorResolver Not a pure module */
