// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  inside: "inside",
  outside: "outside"
};

var MarkerPosition = {
  key: "markerPosition",
  initial: "outside",
  options: options
};

export {
  MarkerPosition ,
  
}
/* No side effect */
