// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarkerPosition from "./MarkerPosition.js";
import * as Css from "@vanilla-extract/css";

var options = MarkerPosition.MarkerPosition.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                listStylePosition: value
              };
      }));

var MarkerPositionStyle_key = MarkerPosition.MarkerPosition.key;

var MarkerPositionStyle_initial = MarkerPosition.MarkerPosition.initial;

var MarkerPositionStyle = {
  key: MarkerPositionStyle_key,
  initial: MarkerPositionStyle_initial,
  options: options,
  style: style
};

export {
  MarkerPositionStyle ,
  
}
/* style Not a pure module */
