// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@vanilla-extract/css";

var style = Css.styleVariants({
      row: "row",
      rowReverse: "row-reverse",
      column: "column",
      columnReverse: "column-Reverse"
    }, (function (value) {
        return {
                flexDirection: value
              };
      }));

function resolve(t) {
  if (t === "row") {
    return style.row;
  } else if (t === "columnReverse") {
    return style.columnReverse;
  } else if (t === "rowReverse") {
    return style.rowReverse;
  } else {
    return style.column;
  }
}

var FlexDirection = {
  initial: "row",
  style: style,
  resolve: resolve
};

export {
  FlexDirection ,
  
}
/* style Not a pure module */
