// Generated by ReScript, PLEASE EDIT WITH CARE

import * as QuoteSize from "./QuoteSize.js";
import * as Css from "@vanilla-extract/css";

var options = QuoteSize.QuoteSize.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--quote-size": value
              };
      }));

var QuoteSizeStyle_initial = QuoteSize.QuoteSize.initial;

var QuoteSizeStyle = {
  initial: QuoteSizeStyle_initial,
  options: options,
  style: style
};

export {
  QuoteSizeStyle ,
  
}
/* style Not a pure module */
