// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: 0,
  xxxsmall: 4,
  xxsmall: 8,
  xsmall: 12,
  small: 16,
  medium: 24,
  large: 36,
  xlarge: 48,
  xxlarge: 96,
  xxxlarge: 128
};

var QuoteSize = {
  initial: "none",
  options: options
};

export {
  QuoteSize ,
  
}
/* No side effect */
