// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextDecorationStyle from "./TextDecorationStyle.js";
import * as Css from "@vanilla-extract/css";

var make = Css.styleVariants(TextDecorationStyle.options, (function (value) {
        return {
                textDecorationStyle: value
              };
      }));

var options = TextDecorationStyle.options;

export {
  options ,
  make ,
  
}
/* make Not a pure module */
