// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  solid: "solid",
  double: "double",
  dotted: "dotted",
  dashed: "dashed",
  wavy: "wavy",
  inherit: "inherit",
  initial: "initial",
  unset: "unset"
};

var TextDecorationStyle = {
  initial: "solid",
  options: options
};

export {
  TextDecorationStyle ,
  
}
/* No side effect */
