// Generated by ReScript, PLEASE EDIT WITH CARE


var args = [
  "solid",
  "initial"
];

var initial = "solid";

var options = {
  solid: "solid",
  initial: "initial"
};

export {
  args ,
  initial ,
  options ,
  
}
/* No side effect */
