// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextDecorationStyle from "./TextDecorationStyle.js";
import * as Css from "@vanilla-extract/css";

var options = TextDecorationStyle.TextDecorationStyle.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                textDecorationStyle: value
              };
      }));

var TextDecorationStyleStyle_key = TextDecorationStyle.TextDecorationStyle.key;

var TextDecorationStyleStyle_initial = TextDecorationStyle.TextDecorationStyle.initial;

var TextDecorationStyleStyle = {
  key: TextDecorationStyleStyle_key,
  initial: TextDecorationStyleStyle_initial,
  options: options,
  style: style
};

export {
  TextDecorationStyleStyle ,
  
}
/* style Not a pure module */
