// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MaxInlineSizeByCharactersStyleCssJs from "./MaxInlineSizeByCharacters/MaxInlineSizeByCharactersStyle.css.js";

var maxInlineSize = MaxInlineSizeByCharactersStyleCssJs.MaxInlineSizeByCharactersStyle;

function resolve(i) {
  var match = i.maxInlineSize;
  return [match === "large" ? maxInlineSize.style.large : (
                match === "medium" ? maxInlineSize.style.medium : (
                    match === "small" ? maxInlineSize.style.small : maxInlineSize.style.none
                  )
              )].join(" ");
}

var MaxInlineSizeByCharactersLayer = {
  resolve: resolve
};

export {
  maxInlineSize ,
  MaxInlineSizeByCharactersLayer ,
  
}
/* maxInlineSize Not a pure module */
