// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.js";
import * as React from "react";
import * as FontLayer from "../../layers/Font/FontLayer.js";
import * as ColorLayer from "../../layers/Color/Color/ColorLayer.js";
import * as TextTransformLayer from "../../layers/Text/Transform/TextTransformLayer.js";
import * as TextDecorationLayer from "../../layers/Text/Decoration/TextDecorationLayer.js";

function make(props) {
  return React.createElement("a", {
              className: Cx.cx([
                    props.className,
                    ColorLayer.ColorLayer.resolve(props.color),
                    FontLayer.FontLayer.resolve(props.fontFamily, props.fontSize, props.fontStyle, props.fontWeight),
                    TextDecorationLayer.TextDecorationLayer.resolve(props.textDecorationColor, props.textDecorationLine, props.textDecorationStyle, props.textDecorationThickness),
                    TextTransformLayer.TextTransformLayer.resolve(props.textTransform)
                  ]),
              href: props.href
            }, props.children);
}

var LinkProto = {
  make: make
};

export {
  LinkProto ,
  
}
/* react Not a pure module */
