// Generated by ReScript, PLEASE EDIT WITH CARE


var LinkDefaultProps = {
  make: {
    color: "primary",
    fontSize: "medium",
    fontWeight: "normal",
    fontFamily: "primary",
    fontStyle: "normal",
    textDecorationColor: "currentColor",
    textDecorationLine: "underline",
    textDecorationStyle: "solid",
    textDecorationThickness: "thin",
    textTransform: "none"
  }
};

export {
  LinkDefaultProps ,
  
}
/* No side effect */
