// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BackgroundClipStyleCssJs from "./Clip/BackgroundClipStyle.css.js";
import * as BackgroundSizeStyleCssJs from "./Size/BackgroundSizeStyle.css.js";
import * as BackgroundColorStyleCssJs from "./Color/BackgroundColorStyle.css.js";
import * as BackgroundOriginStyleCssJs from "./Origin/BackgroundOriginStyle.css.js";
import * as BackgroundRepeatStyleCssJs from "./Repeat/BackgroundRepeatStyle.css.js";
import * as BackgroundOpacityStyleCssJs from "./Opacity/BackgroundOpacityStyle.css.js";
import * as BackgroundPositionStyleCssJs from "./Position/BackgroundPositionStyle.css.js";
import * as BackgroundAttachmentStyleCssJs from "./Attachment/BackgroundAttachmentStyle.css.js";

var backgroundAttachment = BackgroundAttachmentStyleCssJs.BackgroundAttachmentStyle;

var backgroundClip = BackgroundClipStyleCssJs.BackgroundClipStyle;

var backgroundColor = BackgroundColorStyleCssJs.BackgroundColorStyle;

var backgroundOpacity = BackgroundOpacityStyleCssJs.BackgroundOpacityStyle;

var backgroundOrigin = BackgroundOriginStyleCssJs.BackgroundOriginStyle;

var backgroundPosition = BackgroundPositionStyleCssJs.BackgroundPositionStyle;

var backgroundRepeat = BackgroundRepeatStyleCssJs.BackgroundRepeatStyle;

var backgroundSize = BackgroundSizeStyleCssJs.BackgroundSizeStyle;

function resolve(i) {
  var match = i.backgroundAttachment;
  var match$1 = i.backgroundClip;
  var match$2 = i.backgroundColor;
  var match$3 = i.backgroundOpacity;
  var match$4 = i.backgroundOrigin;
  var match$5 = i.backgroundPosition;
  var match$6 = i.backgroundRepeat;
  var match$7 = i.backgroundSize;
  return [
            match === "initial" ? backgroundAttachment.style.initial : (
                match === "local" ? backgroundAttachment.style.local : (
                    match === "fixed" ? backgroundAttachment.style.fixed : (
                        match === "revert" ? backgroundAttachment.style.revert : (
                            match === "unset" ? backgroundAttachment.style.unset : (
                                match === "inherit" ? backgroundAttachment.style.inherit : backgroundAttachment.style.scroll
                              )
                          )
                      )
                  )
              ),
            match$1 === "initial" ? backgroundClip.style.initial : (
                match$1 === "text" ? backgroundClip.style.text : (
                    match$1 === "borderBox" ? backgroundClip.style.borderBox : (
                        match$1 === "revert" ? backgroundClip.style.revert : (
                            match$1 === "unset" ? backgroundClip.style.unset : (
                                match$1 === "inherit" ? backgroundClip.style.inherit : (
                                    match$1 === "paddingBox" ? backgroundClip.style.paddingBox : backgroundClip.style.contentBox
                                  )
                              )
                          )
                      )
                  )
              ),
            match$2 === "secondary" ? backgroundColor.style.secondary : (
                match$2 === "primary" ? backgroundColor.style.primary : (
                    match$2 === "black" ? backgroundColor.style.black : backgroundColor.style.white
                  )
              ),
            match$3 === 10 ? backgroundOpacity.style[10] : (
                match$3 === 20 ? backgroundOpacity.style[20] : (
                    match$3 === 30 ? backgroundOpacity.style[30] : (
                        match$3 === 40 ? backgroundOpacity.style[40] : (
                            match$3 === 50 ? backgroundOpacity.style[50] : (
                                match$3 === 60 ? backgroundOpacity.style[60] : (
                                    match$3 === 70 ? backgroundOpacity.style[70] : (
                                        match$3 === 80 ? backgroundOpacity.style[80] : (
                                            match$3 === 90 ? backgroundOpacity.style[90] : (
                                                match$3 === 100 ? backgroundOpacity.style[100] : backgroundOpacity.style[0]
                                              )
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$4 === "initial" ? backgroundOrigin.style.initial : (
                match$4 === "borderBox" ? backgroundOrigin.style.borderBox : (
                    match$4 === "revert" ? backgroundOrigin.style.revert : (
                        match$4 === "unset" ? backgroundOrigin.style.unset : (
                            match$4 === "inherit" ? backgroundOrigin.style.inherit : (
                                match$4 === "paddingBox" ? backgroundOrigin.style.paddingBox : backgroundOrigin.style.contentBox
                              )
                          )
                      )
                  )
              ),
            match$5 === "initial" ? backgroundPosition.style.initial : (
                match$5 === "bottom" ? backgroundPosition.style.bottom : (
                    match$5 === "right" ? backgroundPosition.style.right : (
                        match$5 === "top" ? backgroundPosition.style.top : (
                            match$5 === "center" ? backgroundPosition.style.center : (
                                match$5 === "revert" ? backgroundPosition.style.revert : (
                                    match$5 === "unset" ? backgroundPosition.style.unset : (
                                        match$5 === "inherit" ? backgroundPosition.style.inherit : backgroundPosition.style.left
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$6 === "initial" ? backgroundRepeat.style.initial : (
                match$6 === "noRepeat" ? backgroundRepeat.style.noRepeat : (
                    match$6 === "round" ? backgroundRepeat.style.round : (
                        match$6 === "space" ? backgroundRepeat.style.space : (
                            match$6 === "repeat" ? backgroundRepeat.style.repeat : (
                                match$6 === "revert" ? backgroundRepeat.style.revert : (
                                    match$6 === "repeat_Space" ? backgroundRepeat.style.repeat_Space : (
                                        match$6 === "round_Space" ? backgroundRepeat.style.round_Space : (
                                            match$6 === "noRepeat_Round" ? backgroundRepeat.style.noRepeat_Round : (
                                                match$6 === "repeatX" ? backgroundRepeat.style.repeatX : (
                                                    match$6 === "repeatY" ? backgroundRepeat.style.repeatY : (
                                                        match$6 === "unset" ? backgroundRepeat.style.unset : (
                                                            match$6 === "inherit" ? backgroundRepeat.style.inherit : backgroundRepeat.style.repeat_Repeat
                                                          )
                                                      )
                                                  )
                                              )
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$7 === "cover" ? backgroundSize.style.cover : (
                match$7 === "initial" ? backgroundSize.style.initial : (
                    match$7 === 50 ? backgroundSize.style[50] : (
                        match$7 === "revert" ? backgroundSize.style.revert : (
                            match$7 === "contain" ? backgroundSize.style.contain : (
                                match$7 === "unset" ? backgroundSize.style.unset : (
                                    match$7 === "inherit" ? backgroundSize.style.inherit : backgroundSize.style.auto
                                  )
                              )
                          )
                      )
                  )
              )
          ].join(" ");
}

var BackgroundLayer = {
  resolve: resolve
};

export {
  backgroundAttachment ,
  backgroundClip ,
  backgroundColor ,
  backgroundOpacity ,
  backgroundOrigin ,
  backgroundPosition ,
  backgroundRepeat ,
  backgroundSize ,
  BackgroundLayer ,
  
}
/* backgroundAttachment Not a pure module */
