// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BorderStyle from "./BorderStyle.js";
import * as Css from "@vanilla-extract/css";

var options = BorderStyle.BorderStyle.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                borderStyle: value
              };
      }));

var BorderStyleStyle_initial = BorderStyle.BorderStyle.initial;

var BorderStyleStyle = {
  initial: BorderStyleStyle_initial,
  options: options,
  style: style
};

export {
  BorderStyleStyle ,
  
}
/* style Not a pure module */
