// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: "none",
  hidden: "hidden",
  dotted: "dotted",
  dashed: "dashed",
  solid: "solid",
  double: "double",
  groove: "groove",
  ridge: "ridge",
  inset: "inset",
  outset: "outset",
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset"
};

var BorderStyle = {
  initial: "none",
  options: options
};

export {
  BorderStyle ,
  
}
/* No side effect */
