// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PaddingBlockEnd from "./PaddingBlockEnd.js";
import * as Css from "@vanilla-extract/css";

var options = PaddingBlockEnd.PaddingBlockEnd.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                paddingBlockEnd: value
              };
      }));

var PaddingBlockEndStyle_initial = PaddingBlockEnd.PaddingBlockEnd.initial;

var PaddingBlockEndStyle_key = PaddingBlockEnd.PaddingBlockEnd.key;

var PaddingBlockEndStyle = {
  initial: PaddingBlockEndStyle_initial,
  options: options,
  key: PaddingBlockEndStyle_key,
  style: style
};

export {
  PaddingBlockEndStyle ,
  
}
/* style Not a pure module */
