// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Padding from "../Padding.js";

var PaddingBlockEnd_initial = Padding.Padding.initial;

var PaddingBlockEnd_options = Padding.Padding.options;

var PaddingBlockEnd = {
  initial: PaddingBlockEnd_initial,
  options: PaddingBlockEnd_options
};

export {
  PaddingBlockEnd ,
  
}
/* No side effect */
