// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PaddingReflection from "../PaddingReflection.js";

var args = PaddingReflection.args;

var initial = PaddingReflection.initial;

export {
  args ,
  initial ,
  
}
/* No side effect */
