// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PaddingReflection from "../PaddingReflection.js";

var PaddingBlockEnd_initial = PaddingReflection.PaddingReflection.initial;

var PaddingBlockEnd_options = PaddingReflection.PaddingReflection.options;

var PaddingBlockEnd = {
  initial: PaddingBlockEnd_initial,
  options: PaddingBlockEnd_options,
  key: "paddingBlockEnd"
};

export {
  PaddingBlockEnd ,
  
}
/* No side effect */
