// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FontFamily from "./FontFamily.js";
import * as Css from "@vanilla-extract/css";

var make = Css.styleVariants(FontFamily.options, (function (value) {
        return {
                fontFamily: value
              };
      }));

var options = FontFamily.options;

export {
  options ,
  make ,
  
}
/* make Not a pure module */
