// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FontFamily from "./FontFamily.js";
import * as Css from "@vanilla-extract/css";

var options = FontFamily.FontFamily.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                fontFamily: value
              };
      }));

var FontFamilyStyle_initial = FontFamily.FontFamily.initial;

var FontFamilyStyle = {
  initial: FontFamilyStyle_initial,
  options: options,
  style: style
};

export {
  FontFamilyStyle ,
  
}
/* style Not a pure module */
