// Generated by ReScript, PLEASE EDIT WITH CARE


var args = ["display"];

var options = {
  display: "Montserrat" + ", \"Open Sans\", Helvetica, Arial, sans-serif"
};

var initial = "display";

var name = {
  display: "Montserrat"
};

export {
  args ,
  initial ,
  name ,
  options ,
  
}
/* No side effect */
