// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  primary: "'Montserrat', Arial, sans-serif",
  monospace: "monospace"
};

var FontFamily = {
  initial: "primary",
  options: options
};

export {
  FontFamily ,
  
}
/* No side effect */
