// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  normal: "normal",
  italic: "italic",
  oblique: "oblique",
  inherit: "inherit",
  initial: "initial",
  unset: "unset"
};

var FontStyle = {
  initial: "normal",
  options: options
};

export {
  FontStyle ,
  
}
/* No side effect */
