// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FontStyle from "./FontStyle.js";
import * as Css from "@vanilla-extract/css";

var make = Css.styleVariants(FontStyle.options, (function (value) {
        return {
                fontStyle: value
              };
      }));

var options = FontStyle.options;

export {
  options ,
  make ,
  
}
/* make Not a pure module */
