// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FontStyle from "./FontStyle.js";
import * as Css from "@vanilla-extract/css";

var options = FontStyle.FontStyle.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                fontStyle: value
              };
      }));

var FontStyleStyle_initial = FontStyle.FontStyle.initial;

var FontStyleStyle = {
  initial: FontStyleStyle_initial,
  options: options,
  style: style
};

export {
  FontStyleStyle ,
  
}
/* style Not a pure module */
