// Generated by ReScript, PLEASE EDIT WITH CARE


var args = ["normal"];

var initial = "normal";

var options = {
  normal: "normal"
};

export {
  args ,
  initial ,
  options ,
  
}
/* No side effect */
