let styleProps: ParagraphProto.styleProps = {
  color: #black,
  fontFamily: #display,
  fontSize: #"2xs",
  fontStyle: #normal,
  fontWeight: #regular,
  lineClamp: #none,
  marginBlockEnd: #size0,
  marginBlockStart: #size0,
  marginInlineEnd: #size0,
  marginInlineStart: #size0,
  paddingBlockEnd: #size250,
  paddingBlockStart: #size250,
  paddingInlineEnd: #size0,
  paddingInlineStart: #size0,
}
