// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  scroll: "scroll",
  fixed: "fixed",
  local: "local",
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset"
};

var BackgroundAttachment = {
  key: "backgroundAttachment",
  initial: "scroll",
  options: options
};

export {
  BackgroundAttachment ,
  
}
/* No side effect */
