// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@vanilla-extract/css";
import * as BackgroundAttachment from "./BackgroundAttachment.js";

var options = BackgroundAttachment.BackgroundAttachment.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                backgroundAttachment: value
              };
      }));

var BackgroundAttachmentStyle_key = BackgroundAttachment.BackgroundAttachment.key;

var BackgroundAttachmentStyle_initial = BackgroundAttachment.BackgroundAttachment.initial;

var BackgroundAttachmentStyle = {
  key: BackgroundAttachmentStyle_key,
  initial: BackgroundAttachmentStyle_initial,
  options: options,
  style: style
};

export {
  BackgroundAttachmentStyle ,
  
}
/* style Not a pure module */
