// Generated by ReScript, PLEASE EDIT WITH CARE

import * as InteractiveColorStyleCssJs from "./InteractiveColorStyle.css.js";

var color = InteractiveColorStyleCssJs.InteractiveColorStyle;

function resolve(i) {
  var match = i.color;
  return [match === "secondary" ? color.style.secondary : (
                match === "primary" ? color.style.primary : (
                    match === "black" ? color.style.black : color.style.white
                  )
              )].join(" ");
}

var InteractiveColorLayer = {
  resolve: resolve
};

export {
  color ,
  InteractiveColorLayer ,
  
}
/* color Not a pure module */
