// Generated by ReScript, PLEASE EDIT WITH CARE

import * as InteractiveColor from "./InteractiveColor.js";
import * as Css from "@vanilla-extract/css";

var options = InteractiveColor.InteractiveColor.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--h": value.hue,
                "--s": value.saturation,
                "--l": value.lightness,
                "--a": value.alpha,
                "--color": "hsl(var(--h) var(--s) var(--l) / var(--a))",
                "--text-color": value.textColor
              };
      }));

var InteractiveColorStyle_key = InteractiveColor.InteractiveColor.key;

var InteractiveColorStyle_initial = InteractiveColor.InteractiveColor.initial;

var InteractiveColorStyle = {
  key: InteractiveColorStyle_key,
  initial: InteractiveColorStyle_initial,
  options: options,
  style: style
};

export {
  InteractiveColorStyle ,
  
}
/* style Not a pure module */
