// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarginReflection from "../MarginReflection.js";

var MarginBlockStart_initial = MarginReflection.MarginReflection.initial;

var MarginBlockStart_options = MarginReflection.MarginReflection.options;

var MarginBlockStart = {
  initial: MarginBlockStart_initial,
  options: MarginBlockStart_options,
  key: "marginBlockStart"
};

export {
  MarginBlockStart ,
  
}
/* No side effect */
