// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Margin from "../Margin.js";

var MarginBlockStart_initial = Margin.Margin.initial;

var MarginBlockStart_options = Margin.Margin.options;

var MarginBlockStart = {
  initial: MarginBlockStart_initial,
  options: MarginBlockStart_options
};

export {
  MarginBlockStart ,
  
}
/* No side effect */
