// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarginBlockStart from "./MarginBlockStart.js";
import * as Css from "@vanilla-extract/css";

var options = MarginBlockStart.MarginBlockStart.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                marginBlockStart: value
              };
      }));

var MarginBlockStartStyle_initial = MarginBlockStart.MarginBlockStart.initial;

var MarginBlockStartStyle = {
  initial: MarginBlockStartStyle_initial,
  options: options,
  style: style
};

export {
  MarginBlockStartStyle ,
  
}
/* style Not a pure module */
