// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: "0px",
  small: "4px",
  medium: "8px",
  large: "12px",
  pill: "9999px",
  circle: "50%"
};

var CornerRadius = {
  initial: "none",
  options: options
};

export {
  CornerRadius ,
  
}
/* No side effect */
