// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CornerRadius from "./CornerRadius.js";
import * as Css from "@vanilla-extract/css";

var options = CornerRadius.CornerRadius.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                borderRadius: value
              };
      }));

var CornerRadiusStyle_key = CornerRadius.CornerRadius.key;

var CornerRadiusStyle_initial = CornerRadius.CornerRadius.initial;

var CornerRadiusStyle = {
  key: CornerRadiusStyle_key,
  initial: CornerRadiusStyle_initial,
  options: options,
  style: style
};

export {
  CornerRadiusStyle ,
  
}
/* style Not a pure module */
