// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: {
    overflow: "initial",
    display: "initial",
    "-webkit-line-clamp": "initial",
    "-webkit-box-orient": "initial"
  },
  "1": {
    overflow: "hidden",
    display: "-webkit-box",
    "-webkit-line-clamp": "1",
    "-webkit-box-orient": "vertical"
  },
  "2": {
    overflow: "hidden",
    display: "-webkit-box",
    "-webkit-line-clamp": "2",
    "-webkit-box-orient": "vertical"
  },
  "3": {
    overflow: "hidden",
    display: "-webkit-box",
    "-webkit-line-clamp": "3",
    "-webkit-box-orient": "vertical"
  },
  "4": {
    overflow: "hidden",
    display: "-webkit-box",
    "-webkit-line-clamp": "4",
    "-webkit-box-orient": "vertical"
  },
  "5": {
    overflow: "hidden",
    display: "-webkit-box",
    "-webkit-line-clamp": "5",
    "-webkit-box-orient": "vertical"
  },
  "6": {
    overflow: "hidden",
    display: "-webkit-box",
    "-webkit-line-clamp": "6",
    "-webkit-box-orient": "vertical"
  }
};

var LineClamp = {
  key: "lineClamp",
  initial: "none",
  options: options
};

export {
  LineClamp ,
  
}
/* No side effect */
