// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LineClamp from "./LineClamp.js";
import * as Css from "@vanilla-extract/css";

var options = LineClamp.LineClamp.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                overflow: value.overflow,
                display: value.display,
                "-webkit-line-clamp": value["-webkit-line-clamp"],
                "-webkit-box-orient": value["-webkit-box-orient"]
              };
      }));

var LineClampStyle_key = LineClamp.LineClamp.key;

var LineClampStyle_initial = LineClamp.LineClamp.initial;

var LineClampStyle = {
  key: LineClampStyle_key,
  initial: LineClampStyle_initial,
  options: options,
  style: style
};

export {
  LineClampStyle ,
  
}
/* style Not a pure module */
