// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BackgroundOpacity from "./BackgroundOpacity.js";
import * as Css from "@vanilla-extract/css";

var options = BackgroundOpacity.BackgroundOpacity.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--background-opacity": value
              };
      }));

var BackgroundOpacityStyle_initial = BackgroundOpacity.BackgroundOpacity.initial;

var BackgroundOpacityStyle = {
  initial: BackgroundOpacityStyle_initial,
  options: options,
  style: style
};

export {
  BackgroundOpacityStyle ,
  
}
/* style Not a pure module */
