// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: "0",
  small: "36ch",
  medium: "48ch",
  large: "64ch"
};

var MaxInlineSizeByCharacters = {
  key: "maxInlineSize",
  initial: "none",
  options: options
};

export {
  MaxInlineSizeByCharacters ,
  
}
/* No side effect */
