// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: "none",
  manual: "manual",
  auto: "auto",
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset"
};

var Hyphens = {
  key: "hyphens",
  initial: "manual",
  options: options
};

export {
  Hyphens ,
  
}
/* No side effect */
