// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hyphens from "./Hyphens.js";
import * as Css from "@vanilla-extract/css";

var options = Hyphens.Hyphens.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                hyphens: value
              };
      }));

var HyphensStyle_key = Hyphens.Hyphens.key;

var HyphensStyle_initial = Hyphens.Hyphens.initial;

var HyphensStyle = {
  key: HyphensStyle_key,
  initial: HyphensStyle_initial,
  options: options,
  style: style
};

export {
  HyphensStyle ,
  
}
/* style Not a pure module */
