// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OverlayColor from "./OverlayColor.js";
import * as Css from "@vanilla-extract/css";

var options = OverlayColor.OverlayColor.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--overlay-color": value
              };
      }));

var OverlayColorStyle_initial = OverlayColor.OverlayColor.initial;

var OverlayColorStyle = {
  initial: OverlayColorStyle_initial,
  options: options,
  style: style
};

export {
  OverlayColorStyle ,
  
}
/* style Not a pure module */
