// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Color from "../../Color/Color/Color.js";

var initial = Color.Color.initial;

var options = {
  primary: "#2B88D8",
  secondary: "#0078D4",
  black: "#FFFFFF",
  white: "#000000"
};

var OverlayColor = {
  initial: initial,
  options: options
};

export {
  OverlayColor ,
  
}
/* No side effect */
