// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OverlayColorStyleCssJs from "./Color/OverlayColorStyle.css.js";

var overlayColor = OverlayColorStyleCssJs.OverlayColorStyle;

function resolve(i) {
  var match = i.overlayColor;
  return [match === "secondary" ? overlayColor.style.secondary : (
                match === "primary" ? overlayColor.style.primary : (
                    match === "black" ? overlayColor.style.black : overlayColor.style.white
                  )
              )].join(" ");
}

var OverlayLayer = {
  resolve: resolve
};

export {
  overlayColor ,
  OverlayLayer ,
  
}
/* overlayColor Not a pure module */
