// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  "0": "0",
  "10": ".1",
  "20": ".2",
  "30": ".3",
  "40": ".4",
  "50": ".5",
  "60": ".6",
  "70": ".7",
  "80": ".8",
  "90": ".9",
  "100": "1"
};

var BorderOpacity = {
  initial: 100,
  options: options
};

export {
  BorderOpacity ,
  
}
/* No side effect */
