// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BorderOpacity from "./BorderOpacity.js";
import * as Css from "@vanilla-extract/css";

var options = BorderOpacity.BorderOpacity.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--border-opacity": value
              };
      }));

var BorderOpacityStyle_key = BorderOpacity.BorderOpacity.key;

var BorderOpacityStyle_initial = BorderOpacity.BorderOpacity.initial;

var BorderOpacityStyle = {
  key: BorderOpacityStyle_key,
  initial: BorderOpacityStyle_initial,
  options: options,
  style: style
};

export {
  BorderOpacityStyle ,
  
}
/* style Not a pure module */
