// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CharsPerLineStyleCssJs from "./CharsPerLine/CharsPerLineStyle.css.js";

var charsPerLine = CharsPerLineStyleCssJs.CharsPerLineStyle;

function resolve(i) {
  var match = i.charsPerLine;
  return [match === "large" ? charsPerLine.style.large : (
                match === "medium" ? charsPerLine.style.medium : (
                    match === "small" ? charsPerLine.style.small : charsPerLine.style.none
                  )
              )].join(" ");
}

var CharsPerLineLayer = {
  resolve: resolve
};

export {
  charsPerLine ,
  CharsPerLineLayer ,
  
}
/* charsPerLine Not a pure module */
