// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  borderBox: "border-box",
  paddingBox: "padding-box",
  contentBox: "content-box",
  text: "text",
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset"
};

var BackgroundClip = {
  key: "backgroundClip",
  initial: "borderBox",
  options: options
};

export {
  BackgroundClip ,
  
}
/* No side effect */
