// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BackgroundClip from "./BackgroundClip.js";
import * as Css from "@vanilla-extract/css";

var options = BackgroundClip.BackgroundClip.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                backgroundClip: value
              };
      }));

var BackgroundClipStyle_initial = BackgroundClip.BackgroundClip.initial;

var BackgroundClipStyle = {
  initial: BackgroundClipStyle_initial,
  options: options,
  style: style
};

export {
  BackgroundClipStyle ,
  
}
/* style Not a pure module */
