// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ButtonLinkVariant from "./ButtonLinkVariant.js";
import * as Css from "@vanilla-extract/css";

var options = ButtonLinkVariant.ButtonLinkVariant.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                color: value.color,
                borderColor: value.borderColor,
                backgroundColor: value.backgroundColor,
                borderStyle: "solid",
                outlineStyle: "none",
                transition: ".2s color ease-in, .2s border ease-in, .2s background ease-in",
                ":hover": value[":hover"],
                ":active": value[":active"],
                ":focus": value[":focus"],
                ":disabled": value[":disabled"]
              };
      }));

var ButtonLinkVariantStyle_key = ButtonLinkVariant.ButtonLinkVariant.key;

var ButtonLinkVariantStyle_initial = ButtonLinkVariant.ButtonLinkVariant.initial;

var ButtonLinkVariantStyle = {
  key: ButtonLinkVariantStyle_key,
  initial: ButtonLinkVariantStyle_initial,
  options: options,
  style: style
};

export {
  ButtonLinkVariantStyle ,
  
}
/* style Not a pure module */
