// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BackgroundColor from "./BackgroundColor.js";
import * as Css from "@vanilla-extract/css";

var options = BackgroundColor.BackgroundColor.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--background-hue": value.hue,
                "--background-saturation": value.saturation,
                "--background-lightness": value.lightness,
                "--background-color": "hsl(var(--background-hue) var(--background-saturation) var(--background-lightness) / var(--background-opacity, 1))",
                backgroundColor: "var(--background-color)"
              };
      }));

var BackgroundColorStyle_key = BackgroundColor.BackgroundColor.key;

var BackgroundColorStyle_initial = BackgroundColor.BackgroundColor.initial;

var BackgroundColorStyle = {
  key: BackgroundColorStyle_key,
  initial: BackgroundColorStyle_initial,
  options: options,
  style: style
};

export {
  BackgroundColorStyle ,
  
}
/* style Not a pure module */
