// Generated by ReScript, PLEASE EDIT WITH CARE

import * as InteractiveSizeStyleCssJs from "./Size/InteractiveSizeStyle.css.js";
import * as InteractiveVariantStyleCssJs from "./Variant/InteractiveVariantStyle.css.js";
import * as InteractiveColorStyleCssJs from "../Color/Interactive/InteractiveColorStyle.css.js";

var interactiveColor = InteractiveColorStyleCssJs.InteractiveColorStyle;

var interactiveSize = InteractiveSizeStyleCssJs.InteractiveSizeStyle;

var interactiveVariant = InteractiveVariantStyleCssJs.InteractiveVariantStyle;

function resolve(i) {
  var match = i.color;
  var match$1 = i.size;
  var match$2 = i.variant;
  return [
            match === "secondary" ? interactiveColor.style.secondary : (
                match === "primary" ? interactiveColor.style.primary : (
                    match === "black" ? interactiveColor.style.black : interactiveColor.style.white
                  )
              ),
            match$1 === "large" ? interactiveSize.style.large : (
                match$1 === "xsmall" ? interactiveSize.style.xsmall : (
                    match$1 === "medium" ? interactiveSize.style.medium : (
                        match$1 === "small" ? interactiveSize.style.small : interactiveSize.style.xlarge
                      )
                  )
              ),
            match$2 === "solid" ? interactiveVariant.style.solid : (
                match$2 === "ghost" ? interactiveVariant.style.ghost : (
                    match$2 === "borderless" ? interactiveVariant.style.borderless : interactiveVariant.style.text
                  )
              )
          ].join(" ");
}

var InteractiveLayer = {
  resolve: resolve
};

export {
  interactiveColor ,
  interactiveSize ,
  interactiveVariant ,
  InteractiveLayer ,
  
}
/* interactiveColor Not a pure module */
