// Generated by ReScript, PLEASE EDIT WITH CARE

import * as InteractiveSizeStyleCssJs from "./Size/InteractiveSizeStyle.css.js";
import * as InteractiveVariantStyleCssJs from "./Variant/InteractiveVariantStyle.css.js";

var interactiveSize = InteractiveSizeStyleCssJs.InteractiveSizeStyle;

var interactiveVariant = InteractiveVariantStyleCssJs.InteractiveVariantStyle;

function resolve(i) {
  var match = i.size;
  var match$1 = i.variant;
  return [
            match === "large" ? interactiveSize.style.large : (
                match === "xsmall" ? interactiveSize.style.xsmall : (
                    match === "medium" ? interactiveSize.style.medium : (
                        match === "small" ? interactiveSize.style.small : interactiveSize.style.xlarge
                      )
                  )
              ),
            match$1 === "solid" ? interactiveVariant.style.solid : (
                match$1 === "ghost" ? interactiveVariant.style.ghost : (
                    match$1 === "borderless" ? interactiveVariant.style.borderless : interactiveVariant.style.text
                  )
              )
          ].join(" ");
}

var InteractiveLayer = {
  resolve: resolve
};

export {
  interactiveSize ,
  interactiveVariant ,
  InteractiveLayer ,
  
}
/* interactiveSize Not a pure module */
