// Generated by ReScript, PLEASE EDIT WITH CARE

import * as InteractiveSizeStyleCssJs from "./Size/InteractiveSizeStyle.css.js";
import * as InteractiveShapeStyleCssJs from "./Shape/InteractiveShapeStyle.css.js";
import * as InteractiveVariantStyleCssJs from "./Variant/InteractiveVariantStyle.css.js";

var interactiveShape = InteractiveShapeStyleCssJs.InteractiveShapeStyle;

var interactiveSize = InteractiveSizeStyleCssJs.InteractiveSizeStyle;

var interactiveVariant = InteractiveVariantStyleCssJs.InteractiveVariantStyle;

function resolve(i) {
  var match = i.interactiveShape;
  var match$1 = i.interactiveSize;
  var match$2 = i.interactiveVariant;
  return [
            match === "square" ? interactiveShape.style.square : (
                match === "fit" ? interactiveShape.style.fit : interactiveShape.style.rect
              ),
            match$1 === "large" ? interactiveSize.style.large : (
                match$1 === "xsmall" ? interactiveSize.style.xsmall : (
                    match$1 === "medium" ? interactiveSize.style.medium : (
                        match$1 === "small" ? interactiveSize.style.small : interactiveSize.style.xlarge
                      )
                  )
              ),
            match$2 === "solid" ? interactiveVariant.style.solid : (
                match$2 === "ghost" ? interactiveVariant.style.ghost : (
                    match$2 === "borderless" ? interactiveVariant.style.borderless : interactiveVariant.style.text
                  )
              )
          ].join(" ");
}

var InteractiveLayer = {
  resolve: resolve
};

export {
  interactiveShape ,
  interactiveSize ,
  interactiveVariant ,
  InteractiveLayer ,
  
}
/* interactiveShape Not a pure module */
