// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BorderThickness from "./BorderThickness.js";
import * as Css from "@vanilla-extract/css";

var options = BorderThickness.BorderThickness.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                borderWidth: value
              };
      }));

var BorderThicknessStyle_initial = BorderThickness.BorderThickness.initial;

var BorderThicknessStyle = {
  initial: BorderThicknessStyle_initial,
  options: options,
  style: style
};

export {
  BorderThicknessStyle ,
  
}
/* style Not a pure module */
