// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: "0px",
  thin: "1px",
  light: "2px",
  medium: "3px",
  bold: "4px"
};

var BorderThickness = {
  initial: "none",
  options: options
};

export {
  BorderThickness ,
  
}
/* No side effect */
