// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AlignContent from "./AlignContent.js";
import * as Css from "@vanilla-extract/css";

var options = AlignContent.AlignContent.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                alignContent: value
              };
      }));

var AlignContentStyle_initial = AlignContent.AlignContent.initial;

var AlignContentStyle = {
  initial: AlignContentStyle_initial,
  options: options,
  style: style
};

export {
  AlignContentStyle ,
  
}
/* style Not a pure module */
