// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  center: "center",
  start: "start",
  end: "end",
  flexStart: "flex-start",
  flexEnd: "flex-end",
  normal: "normal",
  baseline: "baseline",
  firstBaseline: "first baseline",
  lastBaseline: "last baseline",
  spaceBetween: "space-between",
  spaceAround: "space-around",
  spaceEvenly: "space-evenly",
  stretch: "stretch",
  safeCenter: "safe center",
  unsafeCenter: "unsafe center",
  unset: "unset"
};

var AlignContent = {
  initial: "normal",
  options: options
};

export {
  AlignContent ,
  
}
/* No side effect */
