// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarkerSize from "./MarkerSize.js";
import * as Css from "@vanilla-extract/css";

var options = MarkerSize.MarkerSize.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--marker-size": value
              };
      }));

var MarkerSizeStyle_key = MarkerSize.MarkerSize.key;

var MarkerSizeStyle_initial = MarkerSize.MarkerSize.initial;

var MarkerSizeStyle = {
  key: MarkerSizeStyle_key,
  initial: MarkerSizeStyle_initial,
  options: options,
  style: style
};

export {
  MarkerSizeStyle ,
  
}
/* style Not a pure module */
