export { Configurable as H1Configurable, Idiomatic as H1Idiomatic } from './H1'
export { Configurable as H2Configurable, Idiomatic as H2Idiomatic } from './H2'
export { Configurable as H3Configurable, Idiomatic as H3Idiomatic } from './H3'
export { Configurable as H4Configurable, Idiomatic as H4Idiomatic } from './H4'
export { Configurable as H5Configurable, Idiomatic as H5Idiomatic } from './H5'
export { Configurable as H6Configurable, Idiomatic as H6Idiomatic } from './H6'
