// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CharsPerLine from "./CharsPerLine.js";
import * as Css from "@vanilla-extract/css";

var options = CharsPerLine.CharsPerLine.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                maxWidth: value
              };
      }));

var CharsPerLineStyle_initial = CharsPerLine.CharsPerLine.initial;

var CharsPerLineStyle = {
  initial: CharsPerLineStyle_initial,
  options: options,
  style: style
};

export {
  CharsPerLineStyle ,
  
}
/* style Not a pure module */
