// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: "max-content",
  small: "18ch",
  medium: "24ch",
  large: "36ch"
};

var CharsPerLine = {
  key: "charsPerLine",
  initial: "none",
  options: options
};

export {
  CharsPerLine ,
  
}
/* No side effect */
