// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BackgroundPosition from "./BackgroundPosition.js";
import * as Css from "@vanilla-extract/css";

var options = BackgroundPosition.BackgroundPosition.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                backgroundPosition: value
              };
      }));

var BackgroundPositionStyle_initial = BackgroundPosition.BackgroundPosition.initial;

var BackgroundPositionStyle = {
  initial: BackgroundPositionStyle_initial,
  options: options,
  style: style
};

export {
  BackgroundPositionStyle ,
  
}
/* style Not a pure module */
