// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  top: "top",
  bottom: "bottom",
  left: "left",
  right: "right",
  center: "center",
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset"
};

var BackgroundPosition = {
  initial: "center",
  options: options
};

export {
  BackgroundPosition ,
  
}
/* No side effect */
