// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  normal: "normal",
  breakAll: "break-all",
  keepAll: "keep-all",
  breakWord: "break-word",
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset"
};

var WordBreak = {
  key: "wordBreak",
  initial: "normal",
  options: options
};

export {
  WordBreak ,
  
}
/* No side effect */
