// Generated by ReScript, PLEASE EDIT WITH CARE

import * as WordBreak from "./WordBreak.js";
import * as Css from "@vanilla-extract/css";

var options = WordBreak.WordBreak.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                wordBreak: value
              };
      }));

var WordBreakStyle_key = WordBreak.WordBreak.key;

var WordBreakStyle_initial = WordBreak.WordBreak.initial;

var WordBreakStyle = {
  key: WordBreakStyle_key,
  initial: WordBreakStyle_initial,
  options: options,
  style: style
};

export {
  WordBreakStyle ,
  
}
/* style Not a pure module */
