// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  nowrap: "nowrap",
  wrap: "wrap",
  wrapReverse: "wrap-reverse"
};

var FlexWrap = {
  initial: "nowrap",
  options: options
};

export {
  FlexWrap ,
  
}
/* No side effect */
