// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FlexWrap from "./FlexWrap.js";
import * as Css from "@vanilla-extract/css";

var options = FlexWrap.FlexWrap.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                flexWrap: value
              };
      }));

var FlexWrapStyle_initial = FlexWrap.FlexWrap.initial;

var FlexWrapStyle = {
  initial: FlexWrapStyle_initial,
  options: options,
  style: style
};

export {
  FlexWrapStyle ,
  
}
/* style Not a pure module */
