// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ContentAlignStyleCssJs from "./Align/ContentAlignStyle.css.js";

var contentAlign = ContentAlignStyleCssJs.ContentAlignStyle;

function resolve(i) {
  var match = i.contentAlign;
  return [match === "left" ? contentAlign.style.left : (
                match === "initial" ? contentAlign.style.initial : (
                    match === "right" ? contentAlign.style.right : (
                        match === "matchParent" ? contentAlign.style.matchParent : (
                            match === "dot" ? contentAlign.style.dot : (
                                match === "end" ? contentAlign.style.end : (
                                    match === "justify" ? contentAlign.style.justify : (
                                        match === "start" ? contentAlign.style.start : (
                                            match === "center" ? contentAlign.style.center : (
                                                match === "justifyAll" ? contentAlign.style.justifyAll : (
                                                    match === "unset" ? contentAlign.style.unset : (
                                                        match === "inherit" ? contentAlign.style.inherit : contentAlign.style.dotCenter
                                                      )
                                                  )
                                              )
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              )].join(" ");
}

var ContentLayer = {
  resolve: resolve
};

export {
  contentAlign ,
  ContentLayer ,
  
}
/* contentAlign Not a pure module */
