// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cn from "rescript-classnames/src/Cn.js";
import * as TextDecorationLineResolver from "./Line/TextDecorationLineResolver.js";
import * as TextDecorationColorResolver from "./Color/TextDecorationColorResolver.js";
import * as TextDecorationStyleResolver from "./Style/TextDecorationStyleResolver.js";
import * as TextDecorationThicknessResolver from "./Thickness/TextDecorationThicknessResolver.js";

function resolve(textDecorationColor, textDecorationLine, textDecorationStyle, textDecorationThickness) {
  return Cn.make([
              TextDecorationColorResolver.make(textDecorationColor),
              TextDecorationLineResolver.make(textDecorationLine),
              TextDecorationStyleResolver.make(textDecorationStyle),
              TextDecorationThicknessResolver.make(textDecorationThickness)
            ]);
}

export {
  resolve ,
  
}
/* TextDecorationLineResolver Not a pure module */
