// Generated by ReScript, PLEASE EDIT WITH CARE

import * as QuoteSymbol from "./QuoteSymbol.js";
import * as Css from "@vanilla-extract/css";

var options = QuoteSymbol.QuoteSymbol.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--quote-symbol": value
              };
      }));

var QuoteSymbolStyle_initial = QuoteSymbol.QuoteSymbol.initial;

var QuoteSymbolStyle = {
  initial: QuoteSymbolStyle_initial,
  options: options,
  style: style
};

export {
  QuoteSymbolStyle ,
  
}
/* style Not a pure module */
