// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: "none",
  LeftDouble: "\"“\"",
  RightDouble: "\"”\"",
  RightDoubleAngle: "\"»\"",
  LeftDoubleAngle: "\"«\""
};

var QuoteSymbol = {
  key: "quoteSymbol",
  initial: "none",
  options: options
};

export {
  QuoteSymbol ,
  
}
/* No side effect */
