// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@vanilla-extract/css";

var style = Css.styleVariants({
      normal: "normal",
      stretch: "stretch",
      center: "center",
      start: "start",
      end: "end",
      flexStart: "flex-start",
      flexEnd: "flex-end",
      baseline: "baseline",
      firstBaseline: "first baseline",
      lastBaseline: "last baseline",
      safeCenter: "safe center",
      unsafeCenter: "unsafe center",
      unset: "unset"
    }, (function (value) {
        return {
                alignItems: value
              };
      }));

function resolve(t) {
  if (t === "stretch") {
    return style.stretch;
  } else if (t === "end") {
    return style.end;
  } else if (t === "start") {
    return style.start;
  } else if (t === "center") {
    return style.center;
  } else if (t === "firstBaseline") {
    return style.firstBaseline;
  } else if (t === "baseline") {
    return style.baseline;
  } else if (t === "unset") {
    return style.unset;
  } else if (t === "flexStart") {
    return style.flexStart;
  } else if (t === "unsafeCenter") {
    return style.unsafeCenter;
  } else if (t === "normal") {
    return style.normal;
  } else if (t === "flexEnd") {
    return style.flexEnd;
  } else if (t === "safeCenter") {
    return style.safeCenter;
  } else {
    return style.lastBaseline;
  }
}

var AlignItems = {
  initial: "stretch",
  style: style,
  resolve: resolve
};

export {
  AlignItems ,
  
}
/* style Not a pure module */
