// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@vanilla-extract/css";

var style = Css.styleVariants({
      nowrap: "nowrap",
      wrap: "wrap",
      wrapReverse: "wrap-reverse"
    }, (function (value) {
        return {
                flexWrap: value
              };
      }));

function resolve(t) {
  if (t === "wrapReverse") {
    return style.wrapReverse;
  } else if (t === "nowrap") {
    return style.nowrap;
  } else {
    return style.wrap;
  }
}

var FlexWrap = {
  initial: "nowrap",
  style: style,
  resolve: resolve
};

export {
  FlexWrap ,
  
}
/* style Not a pure module */
