// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextDecorationLine from "./TextDecorationLine.js";
import * as Css from "@vanilla-extract/css";

var options = TextDecorationLine.TextDecorationLine.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                textDecorationLine: value
              };
      }));

var TextDecorationLineStyle_initial = TextDecorationLine.TextDecorationLine.initial;

var TextDecorationLineStyle = {
  initial: TextDecorationLineStyle_initial,
  options: options,
  style: style
};

export {
  TextDecorationLineStyle ,
  
}
/* style Not a pure module */
