// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TextDecorationLine from "./TextDecorationLine.js";
import * as Css from "@vanilla-extract/css";

var make = Css.styleVariants(TextDecorationLine.options, (function (value) {
        return {
                textDecorationLine: value
              };
      }));

var options = TextDecorationLine.options;

export {
  options ,
  make ,
  
}
/* make Not a pure module */
