// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: "none",
  underline: "underline",
  overline: "overline",
  lineThrough: "line-through",
  blink: "blink",
  overline_lineThrough: "overline line-through",
  overline_underline: "overline underline",
  lineThrough_underline: "line-through underline",
  overline_lineThrough_underline: "overline line-through underline",
  inherit: "inherit",
  initial: "initial",
  unset: "unset"
};

var TextDecorationLine = {
  initial: "none",
  options: options
};

export {
  TextDecorationLine ,
  
}
/* No side effect */
