// Generated by ReScript, PLEASE EDIT WITH CARE


var args = [
  "none",
  "underline",
  "overline",
  "lineThrough"
];

var initial = "none";

var options = {
  none: "none",
  underline: "underline",
  overline: "overline",
  lineThrough: "line-through"
};

export {
  args ,
  initial ,
  options ,
  
}
/* No side effect */
