// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function LineBreakOpportunity$LineBreakOpportunity(Props) {
  return React.createElement("wbr", undefined);
}

var LineBreakOpportunity = {
  make: LineBreakOpportunity$LineBreakOpportunity
};

export {
  LineBreakOpportunity ,
  
}
/* react Not a pure module */
