// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  primary: {
    hue: "206",
    saturation: "100%",
    lightness: "41.6%"
  },
  secondary: {
    hue: "207.7",
    saturation: "68.9%",
    lightness: "50.8%"
  },
  white: {
    hue: "0",
    saturation: "0%",
    lightness: "100%"
  },
  black: {
    hue: "0",
    saturation: "0%",
    lightness: "0%"
  }
};

var BorderColor = {
  initial: "primary",
  options: options
};

export {
  BorderColor ,
  
}
/* No side effect */
