// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BorderColor from "./BorderColor.js";
import * as Css from "@vanilla-extract/css";

var options = BorderColor.BorderColor.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--border-hue": value.hue,
                "--border-saturation": value.saturation,
                "--border-lightness": value.lightness,
                "--border-color": "hsl(var(--border-hue) var(--border-saturation) var(--border-lightness) / var(--border-opacity, 1))",
                borderColor: "var(--border-color)"
              };
      }));

var BorderColorStyle_initial = BorderColor.BorderColor.initial;

var BorderColorStyle = {
  initial: BorderColorStyle_initial,
  options: options,
  style: style
};

export {
  BorderColorStyle ,
  
}
/* style Not a pure module */
