let styleProps: HeadingProto.styleProps = {
  align: #start,
  color: #black,
  fontFamily: #display,
  fontSize: #s,
  fontStyle: #normal,
  fontWeight: #semiBold,
  marginBlockEnd: #size0,
  marginBlockStart: #size0,
  marginInlineEnd: #size0,
  marginInlineStart: #size0,
  paddingBlockEnd: #size250,
  paddingBlockStart: #size250,
  paddingInlineEnd: #size0,
  paddingInlineStart: #size0,
}
