// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Gap from "./Gap.js";
import * as Css from "@vanilla-extract/css";

var options = Gap.Gap.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                gap: value
              };
      }));

var GapStyle_initial = Gap.Gap.initial;

var GapStyle = {
  initial: GapStyle_initial,
  options: options,
  style: style
};

export {
  GapStyle ,
  
}
/* style Not a pure module */
