// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FontWeight from "./FontWeight.js";
import * as Css from "@vanilla-extract/css";

var make = Css.styleVariants(FontWeight.options, (function (value) {
        return {
                fontWeight: value
              };
      }));

var options = FontWeight.options;

export {
  options ,
  make ,
  
}
/* make Not a pure module */
