// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  thin: "100",
  extraLight: "200",
  light: "300",
  normal: "400",
  medium: "500",
  semiBold: "600",
  bold: "700",
  extraBold: "800",
  heavy: "900",
  lighter: "lighter",
  bolder: "bolder",
  inherit: "inherit",
  initial: "initial",
  unset: "unset"
};

var FontWeight = {
  initial: "normal",
  options: options
};

export {
  FontWeight ,
  
}
/* No side effect */
