// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FontWeight from "./FontWeight.js";
import * as Css from "@vanilla-extract/css";

var options = FontWeight.FontWeight.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                fontWeight: value
              };
      }));

var FontWeightStyle_initial = FontWeight.FontWeight.initial;

var FontWeightStyle = {
  initial: FontWeightStyle_initial,
  options: options,
  style: style
};

export {
  FontWeightStyle ,
  
}
/* style Not a pure module */
