// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var args = [
  "regular",
  "semiBold"
];

var context = React.createContext(undefined);

function useFontWeight(param) {
  return React.useContext(context);
}

var provider = context.Provider;

function FontWeight$component(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var initial = "regular";

var options = {
  regular: "500",
  semiBold: "600"
};

var component = FontWeight$component;

export {
  args ,
  initial ,
  options ,
  context ,
  useFontWeight ,
  provider ,
  component ,
  
}
/* context Not a pure module */
