// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@vanilla-extract/css";

var style = Css.styleVariants({
      none: 0,
      xxxsmall: 4,
      xxsmall: 8,
      xsmall: 12,
      small: 16,
      medium: 24,
      large: 36,
      xlarge: 48,
      xxlarge: 96,
      xxxlarge: 128
    }, (function (value) {
        return {
                gap: value
              };
      }));

function resolve(t) {
  if (t === "none") {
    return style.none;
  } else if (t === "xxlarge") {
    return style.xxlarge;
  } else if (t === "xlarge") {
    return style.xlarge;
  } else if (t === "large") {
    return style.large;
  } else if (t === "xxsmall") {
    return style.xxsmall;
  } else if (t === "xsmall") {
    return style.xsmall;
  } else if (t === "medium") {
    return style.medium;
  } else if (t === "small") {
    return style.small;
  } else if (t === "xxxlarge") {
    return style.xxxlarge;
  } else {
    return style.xxxsmall;
  }
}

var Gap = {
  initial: "none",
  style: style,
  resolve: resolve
};

export {
  Gap ,
  
}
/* style Not a pure module */
