// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BorderColorStyleCssJs from "./Color/BorderColorStyle.css.js";
import * as BorderStyleStyleCssJs from "./Style/BorderStyleStyle.css.js";
import * as BorderOpacityStyleCssJs from "./Opacity/BorderOpacityStyle.css.js";
import * as BorderThicknessStyleCssJs from "./Thickness/BorderThicknessStyle.css.js";

var borderColor = BorderColorStyleCssJs.BorderColorStyle;

var borderOpacity = BorderOpacityStyleCssJs.BorderOpacityStyle;

var borderStyle = BorderStyleStyleCssJs.BorderStyleStyle;

var borderThickness = BorderThicknessStyleCssJs.BorderThicknessStyle;

function resolve(i) {
  var match = i.borderColor;
  var match$1 = i.borderOpacity;
  var match$2 = i.borderStyle;
  var match$3 = i.borderThickness;
  return [
            match === "secondary" ? borderColor.style.secondary : (
                match === "primary" ? borderColor.style.primary : (
                    match === "black" ? borderColor.style.black : borderColor.style.white
                  )
              ),
            match$1 === 10 ? borderOpacity.style[10] : (
                match$1 === 20 ? borderOpacity.style[20] : (
                    match$1 === 30 ? borderOpacity.style[30] : (
                        match$1 === 40 ? borderOpacity.style[40] : (
                            match$1 === 50 ? borderOpacity.style[50] : (
                                match$1 === 60 ? borderOpacity.style[60] : (
                                    match$1 === 70 ? borderOpacity.style[70] : (
                                        match$1 === 80 ? borderOpacity.style[80] : (
                                            match$1 === 90 ? borderOpacity.style[90] : (
                                                match$1 === 100 ? borderOpacity.style[100] : borderOpacity.style[0]
                                              )
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$2 === "initial" ? borderStyle.style.initial : (
                match$2 === "hidden" ? borderStyle.style.hidden : (
                    match$2 === "ridge" ? borderStyle.style.ridge : (
                        match$2 === "solid" ? borderStyle.style.solid : (
                            match$2 === "revert" ? borderStyle.style.revert : (
                                match$2 === "outset" ? borderStyle.style.outset : (
                                    match$2 === "groove" ? borderStyle.style.groove : (
                                        match$2 === "dashed" ? borderStyle.style.dashed : (
                                            match$2 === "unset" ? borderStyle.style.unset : (
                                                match$2 === "inherit" ? borderStyle.style.inherit : (
                                                    match$2 === "dotted" ? borderStyle.style.dotted : (
                                                        match$2 === "double" ? borderStyle.style.double : (
                                                            match$2 === "inset" ? borderStyle.style.inset : borderStyle.style.none
                                                          )
                                                      )
                                                  )
                                              )
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$3 === "none" ? borderThickness.style.none : (
                match$3 === "thin" ? borderThickness.style.thin : (
                    match$3 === "light" ? borderThickness.style.light : (
                        match$3 === "medium" ? borderThickness.style.medium : borderThickness.style.bold
                      )
                  )
              )
          ].join(" ");
}

var BorderLayer = {
  resolve: resolve
};

export {
  borderColor ,
  borderOpacity ,
  borderStyle ,
  borderThickness ,
  BorderLayer ,
  
}
/* borderColor Not a pure module */
