// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  xsmall: {
    paddingBlock: "7px",
    paddingInline: "12px",
    fontSize: "10px",
    borderRadius: "4px",
    borderWidth: "1px",
    outlineOffset: "-4px"
  },
  small: {
    paddingBlock: "10px",
    paddingInline: "16px",
    fontSize: "12px",
    borderRadius: "6px",
    borderWidth: "1px",
    outlineOffset: "-4px"
  },
  medium: {
    paddingBlock: "12px",
    paddingInline: "20px",
    fontSize: "14px",
    borderRadius: "8px",
    borderWidth: "2px",
    outlineOffset: "-8px"
  },
  large: {
    paddingBlock: "18px",
    paddingInline: "24px",
    fontSize: "15px",
    borderRadius: "12px",
    borderWidth: "2px",
    outlineOffset: "-8px"
  },
  xlarge: {
    paddingBlock: "26px",
    paddingInline: "32px",
    fontSize: "16px",
    borderRadius: "16px",
    borderWidth: "2px",
    outlineOffset: "-8px"
  }
};

var InteractiveSize = {
  key: "interactiveSize",
  initial: "medium",
  options: options
};

export {
  InteractiveSize ,
  
}
/* No side effect */
