// Generated by ReScript, PLEASE EDIT WITH CARE

import * as InteractiveSize from "./InteractiveSize.js";
import * as Css from "@vanilla-extract/css";

var options = InteractiveSize.InteractiveSize.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--gap-overlap": value["--gap-overlap"],
                "--spacing-inline": value["--spacing-inline"],
                "--spacing-block": value["--spacing-block"],
                "--font-size": value["--font-size"],
                borderRadius: value.borderRadius,
                borderWidth: value.borderWidth,
                outlineOffset: value.outlineOffset
              };
      }));

var InteractiveSizeStyle_key = InteractiveSize.InteractiveSize.key;

var InteractiveSizeStyle_initial = InteractiveSize.InteractiveSize.initial;

var InteractiveSizeStyle = {
  key: InteractiveSizeStyle_key,
  initial: InteractiveSizeStyle_initial,
  options: options,
  style: style
};

export {
  InteractiveSizeStyle ,
  
}
/* style Not a pure module */
