// Generated by ReScript, PLEASE EDIT WITH CARE

import * as InteractiveSize from "./InteractiveSize.js";
import * as Css from "@vanilla-extract/css";

var options = InteractiveSize.InteractiveSize.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                paddingBlock: value.paddingBlock,
                paddingInline: value.paddingInline,
                fontSize: value.fontSize,
                borderRadius: value.borderRadius,
                borderWidth: value.borderWidth,
                outlineWidth: value.borderWidth,
                outlineOffset: value.outlineOffset
              };
      }));

var InteractiveSizeStyle_key = InteractiveSize.InteractiveSize.key;

var InteractiveSizeStyle_initial = InteractiveSize.InteractiveSize.initial;

var InteractiveSizeStyle = {
  key: InteractiveSizeStyle_key,
  initial: InteractiveSizeStyle_initial,
  options: options,
  style: style
};

export {
  InteractiveSizeStyle ,
  
}
/* style Not a pure module */
