// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  xsmall: {
    "--gap-overlap": "1em",
    "--spacing-inline": "2em",
    "--spacing-block": "1em",
    "--font-size": "0.75em",
    borderRadius: "2px",
    borderWidth: "1px",
    outlineOffset: "-4px"
  },
  small: {
    "--gap-overlap": "1em",
    "--spacing-inline": "2em",
    "--spacing-block": "1em",
    "--font-size": "0.85em",
    borderRadius: "3px",
    borderWidth: "1px",
    outlineOffset: "-4px"
  },
  medium: {
    "--gap-overlap": "1em",
    "--spacing-inline": "2em",
    "--spacing-block": "1em",
    "--font-size": "1em",
    borderRadius: "4px",
    borderWidth: "1px",
    outlineOffset: "-4px"
  },
  large: {
    "--gap-overlap": "1em",
    "--spacing-inline": "2em",
    "--spacing-block": "1em",
    "--font-size": "1.2em",
    borderRadius: "6px",
    borderWidth: "2px",
    outlineOffset: "-4px"
  },
  xlarge: {
    "--gap-overlap": "1em",
    "--spacing-inline": "2em",
    "--spacing-block": "1em",
    "--font-size": "1.5em",
    borderRadius: "8px",
    borderWidth: "2px",
    outlineOffset: "-4px"
  }
};

var InteractiveSize = {
  key: "interactiveSize",
  initial: "medium",
  options: options
};

export {
  InteractiveSize ,
  
}
/* No side effect */
