// Generated by ReScript, PLEASE EDIT WITH CARE


var contentCategories = [
  /* Flow */4,
  /* Phrasing */7
];

var permittedContent = [/* Empty */1];

var implicitARIARole = [/* None */0];

var permittedARIARoles = [
  /* None */0,
  /* Presentation */5
];

var Br = {
  tag: /* Br */3,
  contentCategories: contentCategories,
  permittedContent: permittedContent,
  implicitARIARole: implicitARIARole,
  permittedARIARoles: permittedARIARoles
};

export {
  Br ,
  
}
/* No side effect */
