// Generated by ReScript, PLEASE EDIT WITH CARE


var contentCategories = [
  /* Flow */4,
  /* Phrasing */7,
  /* Palpable */10
];

var permittedContent = [/* Phrasing */7];

var implicitARIARole = [/* Term */16];

var permittedARIARoles = [/* Any */1];

var Dfn = {
  tag: /* Dfn */7,
  contentCategories: contentCategories,
  permittedContent: permittedContent,
  implicitARIARole: implicitARIARole,
  permittedARIARoles: permittedARIARoles
};

export {
  Dfn ,
  
}
/* No side effect */
