// Generated by ReScript, PLEASE EDIT WITH CARE


var contentCategories = [
  /* Flow */4,
  /* Palpable */10
];

var permittedContent = [/* Flow */4];

var implicitARIARole = [/* None */0];

var permittedARIARoles = [/* Any */1];

var Div = {
  tag: /* Div */0,
  contentCategories: contentCategories,
  permittedContent: permittedContent,
  implicitARIARole: implicitARIARole,
  permittedARIARoles: permittedARIARoles
};

export {
  Div ,
  
}
/* No side effect */
