// Generated by ReScript, PLEASE EDIT WITH CARE


var contentCategories = [
  /* Flow */4,
  /* Phrasing */7,
  /* Palpable */10
];

var permittedContent = [/* Phrasing */7];

var implicitARIARole = [/* None */0];

var permittedARIARoles = [/* Any */1];

var Em = {
  tag: /* Em */9,
  contentCategories: contentCategories,
  permittedContent: permittedContent,
  implicitARIARole: implicitARIARole,
  permittedARIARoles: permittedARIARoles
};

export {
  Em ,
  
}
/* No side effect */
