// Generated by ReScript, PLEASE EDIT WITH CARE


var contentCategories = [/* None */0];

var permittedContent = [/* Flow */4];

var implicitARIARole = [/* None */0];

var permittedARIARoles = [
  /* Group */2,
  /* Presentation */5,
  /* None */0
];

var Figcaption = {
  tag: /* Figcaption */10,
  contentCategories: contentCategories,
  permittedContent: permittedContent,
  implicitARIARole: implicitARIARole,
  permittedARIARoles: permittedARIARoles
};

export {
  Figcaption ,
  
}
/* No side effect */
