// Generated by ReScript, PLEASE EDIT WITH CARE


var contentCategories = [
  /* Flow */4,
  /* Heading */6,
  /* Palpable */10
];

var permittedContent = [/* Phrasing */7];

var implicitARIARole = [/* Heading */3];

var permittedARIARoles = [
  /* Tab */4,
  /* Presentation */5,
  /* None */0
];

var H2 = {
  tag: /* H2 */12,
  contentCategories: contentCategories,
  permittedContent: permittedContent,
  implicitARIARole: implicitARIARole,
  permittedARIARoles: permittedARIARoles
};

export {
  H2 ,
  
}
/* No side effect */
