// Generated by ReScript, PLEASE EDIT WITH CARE


var contentCategories = [/* Flow */4];

var permittedContent = [/* Empty */1];

var implicitARIARole = [/* Separator */17];

var permittedARIARoles = [
  /* Presentation */5,
  /* None */0
];

var Hr = {
  tag: /* Hr */17,
  contentCategories: contentCategories,
  permittedContent: permittedContent,
  implicitARIARole: implicitARIARole,
  permittedARIARoles: permittedARIARoles
};

export {
  Hr ,
  
}
/* No side effect */
