// Generated by ReScript, PLEASE EDIT WITH CARE


var contentCategories = [
  /* Flow */4,
  /* Palpable */10
];

var permittedContent = [/* Phrasing */7];

var implicitARIARole = [/* None */0];

var permittedARIARoles = [/* Any */1];

var P = {
  tag: /* P */21,
  contentCategories: contentCategories,
  permittedContent: permittedContent,
  implicitARIARole: implicitARIARole,
  permittedARIARoles: permittedARIARoles
};

export {
  P ,
  
}
/* No side effect */
