// Generated by ReScript, PLEASE EDIT WITH CARE


var contentCategories = [
  /* Flow */4,
  /* Phrasing */7
];

var permittedContent = [/* Phrasing */7];

var implicitARIARole = [/* None */0];

var permittedARIARoles = [/* Any */1];

var Span = {
  tag: /* Span */1,
  contentCategories: contentCategories,
  permittedContent: permittedContent,
  implicitARIARole: implicitARIARole,
  permittedARIARoles: permittedARIARoles
};

export {
  Span ,
  
}
/* No side effect */
