// Generated by ReScript, PLEASE EDIT WITH CARE


var contentCategories = [
  /* Flow */4,
  /* Phrasing */7
];

var permittedContent = [/* Empty */1];

var implicitARIARole = [/* None */0];

var permittedARIARoles = [/* Any */1];

var Wbr = {
  tag: /* Wbr */32,
  contentCategories: contentCategories,
  permittedContent: permittedContent,
  implicitARIARole: implicitARIARole,
  permittedARIARoles: permittedARIARoles
};

export {
  Wbr ,
  
}
/* No side effect */
