// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cn from "rescript-classnames/src/Cn.js";
import * as PaddingInlineEndResolver from "./InlineEnd/PaddingInlineEndResolver.js";
import * as PaddingInlineStartResolver from "./InlineStart/PaddingInlineStartResolver.js";

function resolve(paddingInlineEnd, paddingInlineStart) {
  return Cn.make([
              PaddingInlineEndResolver.make(paddingInlineEnd),
              PaddingInlineStartResolver.make(paddingInlineStart)
            ]);
}

export {
  resolve ,
  
}
/* PaddingInlineEndResolver Not a pure module */
