// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cn from "rescript-classnames/src/Cn.js";
import * as PaddingBlockEndResolver from "./BlockEnd/PaddingBlockEndResolver.js";
import * as PaddingInlineEndResolver from "./InlineEnd/PaddingInlineEndResolver.js";
import * as PaddingBlockStartResolver from "./BlockStart/PaddingBlockStartResolver.js";
import * as PaddingInlineStartResolver from "./InlineStart/PaddingInlineStartResolver.js";

function resolve(paddingBlockEnd, paddingBlockStart, paddingInlineEnd, paddingInlineStart) {
  return Cn.make([
              PaddingBlockEndResolver.make(paddingBlockEnd),
              PaddingBlockStartResolver.make(paddingBlockStart),
              PaddingInlineEndResolver.make(paddingInlineEnd),
              PaddingInlineStartResolver.make(paddingInlineStart)
            ]);
}

export {
  resolve ,
  
}
/* PaddingBlockEndResolver Not a pure module */
