// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PaddingInlineEndStyleCssJs from "./InlineEnd/PaddingInlineEndStyle.css.js";
import * as PaddingInlineStartStyleCssJs from "./InlineStart/PaddingInlineStartStyle.css.js";

var paddingInlineEnd = PaddingInlineEndStyleCssJs.PaddingInlineEndStyle;

var paddingInlineStart = PaddingInlineStartStyleCssJs.PaddingInlineStartStyle;

function resolve(i) {
  var match = i.paddingInlineEnd;
  var match$1 = i.paddingInlineStart;
  return [
            match === "none" ? paddingInlineEnd.style.none : (
                match === "xxlarge" ? paddingInlineEnd.style.xxlarge : (
                    match === "xlarge" ? paddingInlineEnd.style.xlarge : (
                        match === "large" ? paddingInlineEnd.style.large : (
                            match === "xxsmall" ? paddingInlineEnd.style.xxsmall : (
                                match === "xsmall" ? paddingInlineEnd.style.xsmall : (
                                    match === "medium" ? paddingInlineEnd.style.medium : (
                                        match === "small" ? paddingInlineEnd.style.small : (
                                            match === "xxxlarge" ? paddingInlineEnd.style.xxxlarge : paddingInlineEnd.style.xxxsmall
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$1 === "none" ? paddingInlineStart.style.none : (
                match$1 === "xxlarge" ? paddingInlineStart.style.xxlarge : (
                    match$1 === "xlarge" ? paddingInlineStart.style.xlarge : (
                        match$1 === "large" ? paddingInlineStart.style.large : (
                            match$1 === "xxsmall" ? paddingInlineStart.style.xxsmall : (
                                match$1 === "xsmall" ? paddingInlineStart.style.xsmall : (
                                    match$1 === "medium" ? paddingInlineStart.style.medium : (
                                        match$1 === "small" ? paddingInlineStart.style.small : (
                                            match$1 === "xxxlarge" ? paddingInlineStart.style.xxxlarge : paddingInlineStart.style.xxxsmall
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              )
          ].join(" ");
}

var PaddingInlineLayer = {
  resolve: resolve
};

export {
  paddingInlineEnd ,
  paddingInlineStart ,
  PaddingInlineLayer ,
  
}
/* paddingInlineEnd Not a pure module */
