// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PaddingBlockEndStyleCssJs from "./BlockEnd/PaddingBlockEndStyle.css.js";
import * as PaddingInlineEndStyleCssJs from "./InlineEnd/PaddingInlineEndStyle.css.js";
import * as PaddingBlockStartStyleCssJs from "./BlockStart/PaddingBlockStartStyle.css.js";
import * as PaddingInlineStartStyleCssJs from "./InlineStart/PaddingInlineStartStyle.css.js";

var paddingBlockEnd = PaddingBlockEndStyleCssJs.PaddingBlockEndStyle;

var paddingBlockStart = PaddingBlockStartStyleCssJs.PaddingBlockStartStyle;

var paddingInlineEnd = PaddingInlineEndStyleCssJs.PaddingInlineEndStyle;

var paddingInlineStart = PaddingInlineStartStyleCssJs.PaddingInlineStartStyle;

function resolve(i) {
  var match = i.paddingBlockEnd;
  var match$1 = i.paddingBlockStart;
  var match$2 = i.paddingInlineEnd;
  var match$3 = i.paddingInlineStart;
  return [
            match === "none" ? paddingBlockEnd.style.none : (
                match === "xxlarge" ? paddingBlockEnd.style.xxlarge : (
                    match === "xlarge" ? paddingBlockEnd.style.xlarge : (
                        match === "large" ? paddingBlockEnd.style.large : (
                            match === "xxsmall" ? paddingBlockEnd.style.xxsmall : (
                                match === "xsmall" ? paddingBlockEnd.style.xsmall : (
                                    match === "medium" ? paddingBlockEnd.style.medium : (
                                        match === "small" ? paddingBlockEnd.style.small : (
                                            match === "xxxlarge" ? paddingBlockEnd.style.xxxlarge : paddingBlockEnd.style.xxxsmall
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$1 === "none" ? paddingBlockStart.style.none : (
                match$1 === "xxlarge" ? paddingBlockStart.style.xxlarge : (
                    match$1 === "xlarge" ? paddingBlockStart.style.xlarge : (
                        match$1 === "large" ? paddingBlockStart.style.large : (
                            match$1 === "xxsmall" ? paddingBlockStart.style.xxsmall : (
                                match$1 === "xsmall" ? paddingBlockStart.style.xsmall : (
                                    match$1 === "medium" ? paddingBlockStart.style.medium : (
                                        match$1 === "small" ? paddingBlockStart.style.small : (
                                            match$1 === "xxxlarge" ? paddingBlockStart.style.xxxlarge : paddingBlockStart.style.xxxsmall
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$2 === "none" ? paddingInlineEnd.style.none : (
                match$2 === "xxlarge" ? paddingInlineEnd.style.xxlarge : (
                    match$2 === "xlarge" ? paddingInlineEnd.style.xlarge : (
                        match$2 === "large" ? paddingInlineEnd.style.large : (
                            match$2 === "xxsmall" ? paddingInlineEnd.style.xxsmall : (
                                match$2 === "xsmall" ? paddingInlineEnd.style.xsmall : (
                                    match$2 === "medium" ? paddingInlineEnd.style.medium : (
                                        match$2 === "small" ? paddingInlineEnd.style.small : (
                                            match$2 === "xxxlarge" ? paddingInlineEnd.style.xxxlarge : paddingInlineEnd.style.xxxsmall
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$3 === "none" ? paddingInlineStart.style.none : (
                match$3 === "xxlarge" ? paddingInlineStart.style.xxlarge : (
                    match$3 === "xlarge" ? paddingInlineStart.style.xlarge : (
                        match$3 === "large" ? paddingInlineStart.style.large : (
                            match$3 === "xxsmall" ? paddingInlineStart.style.xxsmall : (
                                match$3 === "xsmall" ? paddingInlineStart.style.xsmall : (
                                    match$3 === "medium" ? paddingInlineStart.style.medium : (
                                        match$3 === "small" ? paddingInlineStart.style.small : (
                                            match$3 === "xxxlarge" ? paddingInlineStart.style.xxxlarge : paddingInlineStart.style.xxxsmall
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              )
          ].join(" ");
}

var PaddingLayer = {
  resolve: resolve
};

export {
  paddingBlockEnd ,
  paddingBlockStart ,
  paddingInlineEnd ,
  paddingInlineStart ,
  PaddingLayer ,
  
}
/* paddingBlockEnd Not a pure module */
