// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JustifyContent from "./JustifyContent.js";
import * as Css from "@vanilla-extract/css";

var options = JustifyContent.JustifyContent.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                justifyContent: value
              };
      }));

var JustifyContentStyle_initial = JustifyContent.JustifyContent.initial;

var JustifyContentStyle = {
  initial: JustifyContentStyle_initial,
  options: options,
  style: style
};

export {
  JustifyContentStyle ,
  
}
/* style Not a pure module */
