// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  center: "center",
  start: "start",
  end: "end",
  flexStart: "flex-start",
  flexEnd: "flex-end",
  left: "left",
  right: "right",
  normal: "normal",
  spaceBetween: "space-between",
  spaceAround: "space-around",
  spaceEvenly: "space-evenly",
  stretch: "stretch",
  safeCenter: "safe center",
  unsafeCenter: "unsafe center"
};

var JustifyContent = {
  initial: "flexStart",
  options: options
};

export {
  JustifyContent ,
  
}
/* No side effect */
