// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cx from "rescript-classnames/src/Cx.js";
import * as FontSizeStyleCssJs from "./Size/FontSizeStyle.css.js";
import * as FontStyleStyleCssJs from "./Style/FontStyleStyle.css.js";
import * as FontFamilyStyleCssJs from "./Family/FontFamilyStyle.css.js";
import * as FontWeightStyleCssJs from "./Weight/FontWeightStyle.css.js";

var family = FontFamilyStyleCssJs.FontFamilyStyle;

var size = FontSizeStyleCssJs.FontSizeStyle;

var style = FontStyleStyleCssJs.FontStyleStyle;

var weight = FontWeightStyleCssJs.FontWeightStyle;

function resolve(fontFamily, fontSize, fontStyle, fontWeight) {
  return Cx.cx([
              fontFamily === "primary" ? family.style.primary : family.style.monospace,
              fontSize === "none" ? size.style.none : (
                  fontSize === "larger" ? size.style.larger : (
                      fontSize === "smaller" ? size.style.smaller : (
                          fontSize === "xxlarge" ? size.style.xxlarge : (
                              fontSize === "xlarge" ? size.style.xlarge : (
                                  fontSize === "large" ? size.style.large : (
                                      fontSize === "xxsmall" ? size.style.xxsmall : (
                                          fontSize === "xsmall" ? size.style.xsmall : (
                                              fontSize === "medium" ? size.style.medium : (
                                                  fontSize === "small" ? size.style.small : (
                                                      fontSize === "xxxlarge" ? size.style.xxxlarge : size.style.xxxsmall
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                ),
              fontStyle === "italic" ? style.style.italic : (
                  fontStyle === "unset" ? style.style.unset : (
                      fontStyle === "oblique" ? style.style.oblique : (
                          fontStyle === "inherit" ? style.style.inherit : (
                              fontStyle === "normal" ? style.style.normal : style.style.initial
                            )
                        )
                    )
                ),
              fontWeight === "initial" ? weight.style.initial : (
                  fontWeight === "thin" ? weight.style.thin : (
                      fontWeight === "semiBold" ? weight.style.semiBold : (
                          fontWeight === "bolder" ? weight.style.bolder : (
                              fontWeight === "light" ? weight.style.light : (
                                  fontWeight === "extraBold" ? weight.style.extraBold : (
                                      fontWeight === "extraLight" ? weight.style.extraLight : (
                                          fontWeight === "medium" ? weight.style.medium : (
                                              fontWeight === "lighter" ? weight.style.lighter : (
                                                  fontWeight === "heavy" ? weight.style.heavy : (
                                                      fontWeight === "unset" ? weight.style.unset : (
                                                          fontWeight === "inherit" ? weight.style.inherit : (
                                                              fontWeight === "normal" ? weight.style.normal : weight.style.bold
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            ]);
}

var FontLayer = {
  resolve: resolve
};

export {
  family ,
  size ,
  style ,
  weight ,
  FontLayer ,
  
}
/* family Not a pure module */
