// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FontSizeStyleCssJs from "./Size/FontSizeStyle.css.js";
import * as FontStyleStyleCssJs from "./Style/FontStyleStyle.css.js";
import * as FontFamilyStyleCssJs from "./Family/FontFamilyStyle.css.js";
import * as FontWeightStyleCssJs from "./Weight/FontWeightStyle.css.js";

var fontFamily = FontFamilyStyleCssJs.FontFamilyStyle;

var fontSize = FontSizeStyleCssJs.FontSizeStyle;

var fontStyle = FontStyleStyleCssJs.FontStyleStyle;

var fontWeight = FontWeightStyleCssJs.FontWeightStyle;

function resolve(i) {
  var match = i.fontFamily;
  var match$1 = i.fontSize;
  var match$2 = i.fontStyle;
  var match$3 = i.fontWeight;
  return [
            match === "primary" ? fontFamily.style.primary : fontFamily.style.monospace,
            match$1 === "none" ? fontSize.style.none : (
                match$1 === "larger" ? fontSize.style.larger : (
                    match$1 === "smaller" ? fontSize.style.smaller : (
                        match$1 === "xxlarge" ? fontSize.style.xxlarge : (
                            match$1 === "xlarge" ? fontSize.style.xlarge : (
                                match$1 === "large" ? fontSize.style.large : (
                                    match$1 === "xxsmall" ? fontSize.style.xxsmall : (
                                        match$1 === "xsmall" ? fontSize.style.xsmall : (
                                            match$1 === "medium" ? fontSize.style.medium : (
                                                match$1 === "small" ? fontSize.style.small : (
                                                    match$1 === "xxxlarge" ? fontSize.style.xxxlarge : fontSize.style.xxxsmall
                                                  )
                                              )
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$2 === "italic" ? fontStyle.style.italic : (
                match$2 === "unset" ? fontStyle.style.unset : (
                    match$2 === "oblique" ? fontStyle.style.oblique : (
                        match$2 === "inherit" ? fontStyle.style.inherit : (
                            match$2 === "normal" ? fontStyle.style.normal : fontStyle.style.initial
                          )
                      )
                  )
              ),
            match$3 === "initial" ? fontWeight.style.initial : (
                match$3 === "thin" ? fontWeight.style.thin : (
                    match$3 === "semiBold" ? fontWeight.style.semiBold : (
                        match$3 === "bolder" ? fontWeight.style.bolder : (
                            match$3 === "light" ? fontWeight.style.light : (
                                match$3 === "extraBold" ? fontWeight.style.extraBold : (
                                    match$3 === "extraLight" ? fontWeight.style.extraLight : (
                                        match$3 === "medium" ? fontWeight.style.medium : (
                                            match$3 === "lighter" ? fontWeight.style.lighter : (
                                                match$3 === "heavy" ? fontWeight.style.heavy : (
                                                    match$3 === "unset" ? fontWeight.style.unset : (
                                                        match$3 === "inherit" ? fontWeight.style.inherit : (
                                                            match$3 === "normal" ? fontWeight.style.normal : fontWeight.style.bold
                                                          )
                                                      )
                                                  )
                                              )
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              )
          ].join(" ");
}

var FontLayer = {
  resolve: resolve
};

export {
  fontFamily ,
  fontSize ,
  fontStyle ,
  fontWeight ,
  FontLayer ,
  
}
/* fontFamily Not a pure module */
