// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BackgroundRepeat from "./BackgroundRepeat.js";
import * as Css from "@vanilla-extract/css";

var options = BackgroundRepeat.BackgroundRepeat.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                backgroundRepeat: value
              };
      }));

var BackgroundRepeatStyle_key = BackgroundRepeat.BackgroundRepeat.key;

var BackgroundRepeatStyle_initial = BackgroundRepeat.BackgroundRepeat.initial;

var BackgroundRepeatStyle = {
  key: BackgroundRepeatStyle_key,
  initial: BackgroundRepeatStyle_initial,
  options: options,
  style: style
};

export {
  BackgroundRepeatStyle ,
  
}
/* style Not a pure module */
