// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  repeatX: "repeat-x",
  repeatY: "repeat-y",
  repeat: "repeat",
  space: "space",
  round: "round",
  noRepeat: "no-repeat",
  repeat_Space: "repeat space",
  repeat_Repeat: "repeat repeat",
  round_Space: "round space",
  noRepeat_Round: "no-repeat round",
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset"
};

var BackgroundRepeat = {
  initial: "center",
  options: options
};

export {
  BackgroundRepeat ,
  
}
/* No side effect */
