// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ColorReflection from "../ColorReflection.js";

var options = {
  primary: {
    hue: "218",
    saturation: "100%",
    lightness: "40%",
    alpha: "1",
    textColor: "#fff"
  },
  secondary: {
    hue: "0",
    saturation: "100%",
    lightness: "40%",
    alpha: "1",
    textColor: "#fff"
  },
  white: {
    hue: "0",
    saturation: "0%",
    lightness: "100%",
    alpha: "1",
    textColor: "#000"
  },
  black: {
    hue: "0",
    saturation: "0%",
    lightness: "16.1%",
    alpha: "1",
    textColor: "#fff"
  }
};

var ThemeColor_key = ColorReflection.ColorReflection.key;

var ThemeColor_initial = ColorReflection.ColorReflection.initial;

var ThemeColor = {
  key: ThemeColor_key,
  initial: ThemeColor_initial,
  options: options
};

export {
  ThemeColor ,
  
}
/* No side effect */
