// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ThemeColorStyleCssJs from "./ThemeColorStyle.css.js";

var color = ThemeColorStyleCssJs.ThemeColorStyle;

function resolve(i) {
  var match = i.color;
  return [match === "secondary" ? color.style.secondary : (
                match === "primary" ? color.style.primary : (
                    match === "black" ? color.style.black : color.style.white
                  )
              )].join(" ");
}

var ThemeColorLayer = {
  resolve: resolve
};

export {
  color ,
  ThemeColorLayer ,
  
}
/* color Not a pure module */
