// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Css from "@vanilla-extract/css";
import * as MaxInlineSizeByCharacters from "./MaxInlineSizeByCharacters.js";

var options = MaxInlineSizeByCharacters.MaxInlineSizeByCharacters.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--max-inline-size-by-characters": value
              };
      }));

var MaxInlineSizeByCharactersStyle_initial = MaxInlineSizeByCharacters.MaxInlineSizeByCharacters.initial;

var MaxInlineSizeByCharactersStyle = {
  initial: MaxInlineSizeByCharactersStyle_initial,
  options: options,
  style: style
};

export {
  MaxInlineSizeByCharactersStyle ,
  
}
/* style Not a pure module */
