// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PaddingReflection from "../PaddingReflection.js";
import * as Css from "@vanilla-extract/css";

var make = Css.styleVariants(PaddingReflection.options, (function (value) {
        return {
                paddingInlineEnd: value
              };
      }));

var options = PaddingReflection.options;

export {
  options ,
  make ,
  
}
/* make Not a pure module */
