// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PaddingInlineEnd from "./PaddingInlineEnd.js";
import * as Css from "@vanilla-extract/css";

var options = PaddingInlineEnd.PaddingInlineEnd.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                paddingInlineEnd: value
              };
      }));

var PaddingInlineEndStyle_initial = PaddingInlineEnd.PaddingInlineEnd.initial;

var PaddingInlineEndStyle = {
  initial: PaddingInlineEndStyle_initial,
  options: options,
  style: style
};

export {
  PaddingInlineEndStyle ,
  
}
/* style Not a pure module */
