// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PaddingReflection from "../PaddingReflection.js";

var PaddingInlineEnd_initial = PaddingReflection.PaddingReflection.initial;

var PaddingInlineEnd_options = PaddingReflection.PaddingReflection.options;

var PaddingInlineEnd = {
  initial: PaddingInlineEnd_initial,
  options: PaddingInlineEnd_options,
  key: "paddingInlineEnd"
};

export {
  PaddingInlineEnd ,
  
}
/* No side effect */
