// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Padding from "../Padding.js";

var PaddingInlineEnd_initial = Padding.Padding.initial;

var PaddingInlineEnd_options = Padding.Padding.options;

var PaddingInlineEnd = {
  initial: PaddingInlineEnd_initial,
  options: PaddingInlineEnd_options
};

export {
  PaddingInlineEnd ,
  
}
/* No side effect */
