// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function LineBreak$LineBreak(Props) {
  return React.createElement("br", undefined);
}

var LineBreak = {
  make: LineBreak$LineBreak
};

export {
  LineBreak ,
  
}
/* react Not a pure module */
