// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function LineBreak(Props) {
  return React.createElement("br", undefined);
}

var make = LineBreak;

export {
  make ,
  
}
/* react Not a pure module */
