// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: "none",
  bullet: "\"•\"",
  circle: "\"●\""
};

var MarkerSymbol = {
  initial: "bullet",
  options: options
};

export {
  MarkerSymbol ,
  
}
/* No side effect */
