// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarkerSymbol from "./MarkerSymbol.js";
import * as Css from "@vanilla-extract/css";

var options = MarkerSymbol.MarkerSymbol.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--marker-symbol": value,
                listStyleType: value
              };
      }));

var MarkerSymbolStyle_initial = MarkerSymbol.MarkerSymbol.initial;

var MarkerSymbolStyle = {
  initial: MarkerSymbolStyle_initial,
  options: options,
  style: style
};

export {
  MarkerSymbolStyle ,
  
}
/* style Not a pure module */
