// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  left: "left",
  right: "right",
  center: "center",
  justify: "justify",
  justifyAll: "justify-all",
  start: "start",
  end: "end",
  matchParent: "match-parent",
  dot: "\".\"",
  dotCenter: "\".\" center",
  inherit: "inherit",
  initial: "initial",
  unset: "unset"
};

var ContentAlign = {
  initial: "start",
  options: options
};

export {
  ContentAlign ,
  
}
/* No side effect */
