// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ContentAlign from "./ContentAlign.js";
import * as Css from "@vanilla-extract/css";

var options = ContentAlign.ContentAlign.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                textAlign: value
              };
      }));

var ContentAlignStyle_initial = ContentAlign.ContentAlign.initial;

var ContentAlignStyle = {
  initial: ContentAlignStyle_initial,
  options: options,
  style: style
};

export {
  ContentAlignStyle ,
  
}
/* style Not a pure module */
