// Generated by ReScript, PLEASE EDIT WITH CARE

import * as BackgroundSize from "./BackgroundSize.js";
import * as Css from "@vanilla-extract/css";

var options = BackgroundSize.BackgroundSize.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                backgroundSize: value
              };
      }));

var BackgroundSizeStyle_initial = BackgroundSize.BackgroundSize.initial;

var BackgroundSizeStyle = {
  initial: BackgroundSizeStyle_initial,
  options: options,
  style: style
};

export {
  BackgroundSizeStyle ,
  
}
/* style Not a pure module */
