// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  cover: "cover",
  contain: "contain",
  "50": "50%",
  auto: "auto",
  inherit: "inherit",
  initial: "initial",
  revert: "revert",
  unset: "unset"
};

var BackgroundSize = {
  initial: "auto",
  options: options
};

export {
  BackgroundSize ,
  
}
/* No side effect */
