// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Margin from "../Margin.js";

var MarginInlineStart_initial = Margin.Margin.initial;

var MarginInlineStart_options = Margin.Margin.options;

var MarginInlineStart = {
  initial: MarginInlineStart_initial,
  options: MarginInlineStart_options
};

export {
  MarginInlineStart ,
  
}
/* No side effect */
