// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarginReflection from "../MarginReflection.js";

var MarginInlineStart_initial = MarginReflection.MarginReflection.initial;

var MarginInlineStart_options = MarginReflection.MarginReflection.options;

var MarginInlineStart = {
  initial: MarginInlineStart_initial,
  options: MarginInlineStart_options,
  key: "marginInlineStart"
};

export {
  MarginInlineStart ,
  
}
/* No side effect */
