// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarginInlineStart from "./MarginInlineStart.js";
import * as Css from "@vanilla-extract/css";

var options = MarginInlineStart.MarginInlineStart.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                marginInlineStart: value
              };
      }));

var MarginInlineStartStyle_initial = MarginInlineStart.MarginInlineStart.initial;

var MarginInlineStartStyle = {
  initial: MarginInlineStartStyle_initial,
  options: options,
  style: style
};

export {
  MarginInlineStartStyle ,
  
}
/* style Not a pure module */
