// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarginReflection from "../MarginReflection.js";

var args = MarginReflection.args;

var initial = MarginReflection.initial;

export {
  args ,
  initial ,
  
}
/* No side effect */
