// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  none: "0px",
  xxxsmall: "clamp(" + String(0) + "rem, calc(" + String(0) + "rem + ((1vw - 0.48rem) * 0.3472)), " + String(0 * 1.5) + "rem)",
  xxsmall: "clamp(" + String(0) + "rem, calc(" + String(0) + "rem + ((1vw - 0.48rem) * 0.3472)), " + String(0 * 1.5) + "rem)",
  xsmall: "clamp(" + String(0) + "rem, calc(" + String(0) + "rem + ((1vw - 0.48rem) * 0.3472)), " + String(0 * 1.5) + "rem)",
  small: "clamp(" + String(1) + "rem, calc(" + String(1) + "rem + ((1vw - 0.48rem) * 0.3472)), " + String(1 * 1.5) + "rem)",
  medium: "clamp(" + String(1) + "rem, calc(" + String(1) + "rem + ((1vw - 0.48rem) * 0.3472)), " + String(1 * 1.5) + "rem)",
  large: "clamp(" + String(2) + "rem, calc(" + String(2) + "rem + ((1vw - 0.48rem) * 0.3472)), " + String(2 * 1.5) + "rem)",
  xlarge: "clamp(" + String(3) + "rem, calc(" + String(3) + "rem + ((1vw - 0.48rem) * 0.3472)), " + String(3 * 1.5) + "rem)",
  xxlarge: "clamp(" + String(6) + "rem, calc(" + String(6) + "rem + ((1vw - 0.48rem) * 0.3472)), " + String(6 * 1.5) + "rem)",
  xxxlarge: "clamp(" + String(8) + "rem, calc(" + String(8) + "rem + ((1vw - 0.48rem) * 0.3472)), " + String(8 * 1.5) + "rem)",
  smaller: "smaller",
  larger: "larger"
};

var FontSize = {
  initial: "none",
  options: options
};

export {
  FontSize ,
  
}
/* options Not a pure module */
