// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var args = [
  "none",
  "5xs",
  "4xs",
  "3xs",
  "2xs",
  "xs",
  "s",
  "m",
  "l",
  "xl",
  "2xl",
  "3xl",
  "4xl",
  "5xl"
];

var context = React.createContext(undefined);

function useFontSize(param) {
  return React.useContext(context);
}

var provider = context.Provider;

function FontSize$component(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var initial = "m";

var options = {
  none: 0,
  "5xs": 10,
  "4xs": 12,
  "3xs": 14,
  "2xs": 15,
  xs: 16,
  s: 18,
  m: 20,
  l: 24,
  xl: 26,
  "2xl": 30,
  "3xl": 38,
  "4xl": 46,
  "5xl": 60
};

var component = FontSize$component;

export {
  args ,
  initial ,
  options ,
  context ,
  useFontSize ,
  provider ,
  component ,
  
}
/* context Not a pure module */
