// Generated by ReScript, PLEASE EDIT WITH CARE

import * as FontSize from "./FontSize.js";
import * as Css from "@vanilla-extract/css";

var options = FontSize.FontSize.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                lineHeight: "1.2",
                fontSize: value
              };
      }));

var FontSizeStyle_initial = FontSize.FontSize.initial;

var FontSizeStyle = {
  initial: FontSizeStyle_initial,
  options: options,
  style: style
};

export {
  FontSizeStyle ,
  
}
/* style Not a pure module */
