// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  normal: "normal",
  stretch: "stretch",
  center: "center",
  start: "start",
  end: "end",
  flexStart: "flex-start",
  flexEnd: "flex-end",
  baseline: "baseline",
  firstBaseline: "first baseline",
  lastBaseline: "last baseline",
  safeCenter: "safe center",
  unsafeCenter: "unsafe center",
  unset: "unset"
};

var AlignItems = {
  initial: "stretch",
  options: options
};

export {
  AlignItems ,
  
}
/* No side effect */
