// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AlignItems from "./AlignItems.js";
import * as Css from "@vanilla-extract/css";

var options = AlignItems.AlignItems.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                alignItems: value
              };
      }));

var AlignItemsStyle_initial = AlignItems.AlignItems.initial;

var AlignItemsStyle = {
  initial: AlignItemsStyle_initial,
  options: options,
  style: style
};

export {
  AlignItemsStyle ,
  
}
/* style Not a pure module */
