// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PaddingReflection from "../PaddingReflection.js";

var PaddingInlineStart_initial = PaddingReflection.PaddingReflection.initial;

var PaddingInlineStart_options = PaddingReflection.PaddingReflection.options;

var PaddingInlineStart = {
  initial: PaddingInlineStart_initial,
  options: PaddingInlineStart_options,
  key: "paddingInlineStart"
};

export {
  PaddingInlineStart ,
  
}
/* No side effect */
