// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PaddingInlineStart from "./PaddingInlineStart.js";
import * as Css from "@vanilla-extract/css";

var options = PaddingInlineStart.PaddingInlineStart.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                paddingInlineStart: value
              };
      }));

var PaddingInlineStartStyle_initial = PaddingInlineStart.PaddingInlineStart.initial;

var PaddingInlineStartStyle_key = PaddingInlineStart.PaddingInlineStart.key;

var PaddingInlineStartStyle = {
  initial: PaddingInlineStartStyle_initial,
  options: options,
  key: PaddingInlineStartStyle_key,
  style: style
};

export {
  PaddingInlineStartStyle ,
  
}
/* style Not a pure module */
