// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Padding from "../Padding.js";

var PaddingInlineStart_initial = Padding.Padding.initial;

var PaddingInlineStart_options = Padding.Padding.options;

var PaddingInlineStart = {
  initial: PaddingInlineStart_initial,
  options: PaddingInlineStart_options
};

export {
  PaddingInlineStart ,
  
}
/* No side effect */
