// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarkerGap from "./MarkerGap.js";
import * as Css from "@vanilla-extract/css";

var options = MarkerGap.MarkerGap.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                "--marker-gap": value
              };
      }));

var MarkerGapStyle_initial = MarkerGap.MarkerGap.initial;

var MarkerGapStyle = {
  initial: MarkerGapStyle_initial,
  options: options,
  style: style
};

export {
  MarkerGapStyle ,
  
}
/* style Not a pure module */
