// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarkerGapStyleCssJs from "./Gap/MarkerGapStyle.css.js";
import * as MarkerSizeStyleCssJs from "./Size/MarkerSizeStyle.css.js";
import * as MarkerSymbolStyleCssJs from "./Symbol/MarkerSymbolStyle.css.js";
import * as MarkerPositionStyleCssJs from "./Position/MarkerPositionStyle.css.js";

var markerGap = MarkerGapStyleCssJs.MarkerGapStyle;

var markerPosition = MarkerPositionStyleCssJs.MarkerPositionStyle;

var markerSize = MarkerSizeStyleCssJs.MarkerSizeStyle;

var markerSymbol = MarkerSymbolStyleCssJs.MarkerSymbolStyle;

function resolve(i) {
  var match = i.markerGap;
  var match$1 = i.markerPosition;
  var match$2 = i.markerSize;
  var match$3 = i.markerSymbol;
  return [
            match === "none" ? markerGap.style.none : (
                match === "xxlarge" ? markerGap.style.xxlarge : (
                    match === "xlarge" ? markerGap.style.xlarge : (
                        match === "large" ? markerGap.style.large : (
                            match === "xxsmall" ? markerGap.style.xxsmall : (
                                match === "xsmall" ? markerGap.style.xsmall : (
                                    match === "medium" ? markerGap.style.medium : (
                                        match === "small" ? markerGap.style.small : (
                                            match === "xxxlarge" ? markerGap.style.xxxlarge : markerGap.style.xxxsmall
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$1 === "inside" ? markerPosition.style.inside : markerPosition.style.outside,
            match$2 === "none" ? markerSize.style.none : (
                match$2 === "xxlarge" ? markerSize.style.xxlarge : (
                    match$2 === "xlarge" ? markerSize.style.xlarge : (
                        match$2 === "large" ? markerSize.style.large : (
                            match$2 === "xxsmall" ? markerSize.style.xxsmall : (
                                match$2 === "xsmall" ? markerSize.style.xsmall : (
                                    match$2 === "medium" ? markerSize.style.medium : (
                                        match$2 === "small" ? markerSize.style.small : (
                                            match$2 === "xxxlarge" ? markerSize.style.xxxlarge : markerSize.style.xxxsmall
                                          )
                                      )
                                  )
                              )
                          )
                      )
                  )
              ),
            match$3 === "bullet" ? markerSymbol.style.bullet : (
                match$3 === "circle" ? markerSymbol.style.circle : markerSymbol.style.none
              )
          ].join(" ");
}

var MarkerLayer = {
  resolve: resolve
};

export {
  markerGap ,
  markerPosition ,
  markerSize ,
  markerSymbol ,
  MarkerLayer ,
  
}
/* markerGap Not a pure module */
