// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CornerRadiusStyleCssJs from "./Radius/CornerRadiusStyle.css.js";

var cornerRadius = CornerRadiusStyleCssJs.CornerRadiusStyle;

function resolve(i) {
  var match = i.cornerRadius;
  return [match === "pill" ? cornerRadius.style.pill : (
                match === "circle" ? cornerRadius.style.circle : (
                    match === "xlarge" ? cornerRadius.style.xlarge : (
                        match === "large" ? cornerRadius.style.large : (
                            match === "xsmall" ? cornerRadius.style.xsmall : (
                                match === "medium" ? cornerRadius.style.medium : (
                                    match === "small" ? cornerRadius.style.small : cornerRadius.style.none
                                  )
                              )
                          )
                      )
                  )
              )].join(" ");
}

var CornerLayer = {
  resolve: resolve
};

export {
  cornerRadius ,
  CornerLayer ,
  
}
/* cornerRadius Not a pure module */
