// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarginBlockEnd from "./MarginBlockEnd.js";
import * as Css from "@vanilla-extract/css";

var options = MarginBlockEnd.MarginBlockEnd.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                marginBlockEnd: value
              };
      }));

var MarginBlockEndStyle_initial = MarginBlockEnd.MarginBlockEnd.initial;

var MarginBlockEndStyle_key = MarginBlockEnd.MarginBlockEnd.key;

var MarginBlockEndStyle = {
  initial: MarginBlockEndStyle_initial,
  options: options,
  key: MarginBlockEndStyle_key,
  style: style
};

export {
  MarginBlockEndStyle ,
  
}
/* style Not a pure module */
