// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Margin from "../Margin.js";

var MarginBlockEnd_initial = Margin.Margin.initial;

var MarginBlockEnd_options = Margin.Margin.options;

var MarginBlockEnd = {
  initial: MarginBlockEnd_initial,
  options: MarginBlockEnd_options
};

export {
  MarginBlockEnd ,
  
}
/* No side effect */
