// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MarginReflection from "../MarginReflection.js";

var MarginBlockEnd_initial = MarginReflection.MarginReflection.initial;

var MarginBlockEnd_options = MarginReflection.MarginReflection.options;

var MarginBlockEnd = {
  initial: MarginBlockEnd_initial,
  options: MarginBlockEnd_options,
  key: "marginBlockEnd"
};

export {
  MarginBlockEnd ,
  
}
/* No side effect */
