// Generated by ReScript, PLEASE EDIT WITH CARE


var options = {
  rect: {
    height: "var(--size)",
    minHeight: "initial",
    maxHeight: "initial",
    width: "initial",
    minWidth: "initial",
    maxWidth: "initial"
  },
  square: {
    height: "var(--size)",
    minHeight: "var(--size)",
    maxHeight: "var(--size)",
    width: "var(--size)",
    minWidth: "var(--size)",
    maxWidth: "var(--size)"
  },
  fit: {
    height: "var(--size)",
    minHeight: "initial",
    maxHeight: "initial",
    width: "fit-content",
    minWidth: "fit-content",
    maxWidth: "fit-content"
  }
};

var InteractiveShape = {
  key: "interactiveShape",
  initial: "rect",
  options: options
};

export {
  InteractiveShape ,
  
}
/* No side effect */
