// Generated by ReScript, PLEASE EDIT WITH CARE

import * as InteractiveShape from "./InteractiveShape.js";
import * as Css from "@vanilla-extract/css";

var options = InteractiveShape.InteractiveShape.options;

var style = Css.styleVariants(options, (function (value) {
        return {
                height: value.height,
                minHeight: value.minHeight,
                maxHeight: value.maxHeight,
                width: value.width,
                minWidth: value.minWidth,
                maxWidth: value.maxWidth
              };
      }));

var InteractiveShapeStyle_key = InteractiveShape.InteractiveShape.key;

var InteractiveShapeStyle_initial = InteractiveShape.InteractiveShape.initial;

var InteractiveShapeStyle = {
  key: InteractiveShapeStyle_key,
  initial: InteractiveShapeStyle_initial,
  options: options,
  style: style
};

export {
  InteractiveShapeStyle ,
  
}
/* style Not a pure module */
